// Banco de dados de receitas - Conteúdo original e exclusivo
// Cada receita foi reescrita para ser única e evitar plágio

export interface Recipe {
  id: string;
  titulo: string;
  descricao: string;
  categoria: string;
  tempoPreparo: number; // em minutos
  tempoTotal: number; // em minutos
  porcoes: number;
  dificuldade: 'fácil' | 'médio' | 'difícil';
  ingredientes: {
    item: string;
    quantidade: string;
  }[];
  modoPreparo: string[];
  dicas: string[];
  imagem: string;
  slug: string;
  receitasRelacionadas?: string[]; // IDs de receitas relacionadas (4-5)
  categoriasRelacionadas?: string[]; // categorias relacionadas
}

export const recipes: Recipe[] = [
  {
    id: '1',
    titulo: 'Bolo de Chocolate da Lurdinha',
    descricao: 'Esse bolo de chocolate é o que eu faço quando a casa pede um cheirinho de infância, um bolo macio e úmido que a criançada devora em minutos.',
    categoria: 'Bolos',
    tempoPreparo: 20,
    tempoTotal: 50,
    porcoes: 8,
    dificuldade: 'médio',
    ingredientes: [
      { item: 'Chocolate em pó de qualidade', quantidade: '3/4 xícara' },
      { item: 'Farinha de trigo', quantidade: '1 1/2 xícara' },
      { item: 'Açúcar cristal', quantidade: '1 xícara' },
      { item: 'Ovos grandes', quantidade: '3 unidades' },
      { item: 'Óleo vegetal', quantidade: '1/2 xícara' },
      { item: 'Leite integral', quantidade: '3/4 xícara' },
      { item: 'Fermento químico', quantidade: '2 colheres de chá' },
      { item: 'Sal refinado', quantidade: '1/4 colher de chá' },
      { item: 'Extrato de baunilha', quantidade: '1 colher de chá' },
    ],
    modoPreparo: [
      'Pré-aqueça o forno a 180°C. Unte uma forma redonda de 20cm com manteiga e polvilhe farinha para não grudar.',
      'Numa tigela grande, peneire a farinha, o chocolate em pó, o açúcar, o fermento e o sal. A gosto vai acompanhar aqui.',
      'Em outro bowl, bata os ovos com o óleo até ficar lisinho e bonito.',
      'Vá juntando a mistura de ovos aos secos, mexendo devagar para não fazer farofa.',
      'Adicione o leite morno e a baunilha, mexendo até a massa ficar lisa e brilhante.',
      'Despeje na forma e leve ao forno por 30 a 35 minutos. O palito deve sair com pouquinhos fios úmidos, que é o segredo do bolo úmido.',
      'Espere 10 minutos antes de desenformar, senão ele desmancha de tão mole.',
    ],
    dicas: [
      'Chocolate em pó de marca boa faz toda a diferença no sabor, eu não economizo nisso',
      'Abrir o forno antes dos 25 minutos pode mofar a massa, então segure a ansiedade',
      'Se quiser, cubra com uma ganache simples de chocolate e creme de leite no dia seguinte',
    ],
    imagem: '/images/bolo-chocolate.jpg',
    slug: 'bolo-chocolate-intenso',
    receitasRelacionadas: ['12', '21', '22', '23'],
    categoriasRelacionadas: ['Bolos', 'Doces'],
  },
  {
    id: '2',
    titulo: 'Frango Grelhado no Tempero que a Lurdinha Guarda à Sete Chaves',
    descricao: 'Quando sobra peito de frango na geladeira, essa marinada vira herói do almoço. Meus netos dizem que a casa fica com cheiro de restaurante.',
    categoria: 'Pratos Principais',
    tempoPreparo: 30,
    tempoTotal: 45,
    porcoes: 4,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Peito de frango', quantidade: '4 filés (600g)' },
      { item: 'Suco de limão fresco', quantidade: '1/4 xícara' },
      { item: 'Azeite extra virgem', quantidade: '3 colheres de sopa' },
      { item: 'Alho picado', quantidade: '4 dentes' },
      { item: 'Orégano seco', quantidade: '1 colher de chá' },
      { item: 'Tomilho fresco', quantidade: '1 colher de sopa' },
      { item: 'Sal marinho', quantidade: 'a gosto' },
      { item: 'Pimenta preta moída', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Numa tigela, misture o suco de limão, o azeite, o alho, o orégano, o tomilho picadinho, sal e pimenta. O cheiro já vai te conquistar.',
      'Coloque os filés num pote ou saco e despeje a marinada por cima, massageando cada pedaço.',
      'Deixe na geladeira por pelo menos 20 minutos. Se puder deixar 2 horas, fica melhor ainda.',
      'Aqueça a frigideira ou grelha em fogo alto até quase fumar.',
      'Tire o frango da marinada, escorra o excesso e coloque para selar. Douro 6 a 7 minutos de cada lado.',
      'Para ter certeza, espete um termômetro: 75°C no centro é o ponto seguro.',
      'Tire do fogo e deixe descansar 5 minutinhos para o suco não escorrer todo.',
    ],
    dicas: [
      'Tire o frango da geladeira 10 minutos antes de grelhar para a carne não encolher',
      'Vire uma ou duas vezes, no máximo, senão o peito fica ressecado',
      'Depois de pronto, cubra com papel-alumínio para manter o suco enquanto monta o prato',
    ],
    imagem: '/images/frango-grelhado.jpg',
    slug: 'frango-grelhado-tempero-especial',
    receitasRelacionadas: ['3', '8', '9', '10'],
    categoriasRelacionadas: ['Pratos Principais', 'Frutos do Mar'],
  },
  {
    id: '3',
    titulo: 'Salada Tropical da Lurdinha para Dias de Calor',
    descricao: 'Essa salada nasceu num domingo em que eu não queria ligar o fogão. Manga, abacaxi e morango com folhas frescas viram almoço de rainha.',
    categoria: 'Saladas',
    tempoPreparo: 15,
    tempoTotal: 15,
    porcoes: 4,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Folhas de alface roxa', quantidade: '2 xícaras' },
      { item: 'Rúcula fresca', quantidade: '1 xícara' },
      { item: 'Manga madura', quantidade: '1 unidade' },
      { item: 'Abacaxi fresco', quantidade: '1 xícara' },
      { item: 'Morango', quantidade: '200g' },
      { item: 'Coco ralado fresco', quantidade: '1/4 xícara' },
      { item: 'Suco de laranja', quantidade: '1/4 xícara' },
      { item: 'Suco de limão', quantidade: '2 colheres de sopa' },
      { item: 'Azeite suave', quantidade: '3 colheres de sopa' },
      { item: 'Mel puro', quantidade: '1 colher de sopa' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Lave as folhas e seque bem com papel-toalha. Folha molhada estraga o prato.',
      'Corte a manga em cubinhos, o abacaxi em pedaços pequenos e tire aquele miolo duro.',
      'Lave os morangos, tire o cabinho e corte em fatias.',
      'Numa jarra, bata o suco de laranja, o limão, o azeite, o mel, sal e pimenta. Prove para ver se está no ponto.',
      'Numa tigela grande, comece com as folhas verdes.',
      'Espalhe a manga, o abacaxi e os morangos por cima, colorindo bem.',
      'Polvilhe o coco ralado que lembra praia.',
      'Só despeje o molho na hora de levar à mesa, senão murcha tudo.',
    ],
    dicas: [
      'Faça o vinagrete de manhã e deixe na geladeira, os sabores casam melhor assim',
      'Frutas bem maduras dão aquele doce natural que nenhum açúcar consegue',
      'Se quiser, adicione queijo coalho grelhado para transformar em refeição completa',
    ],
    imagem: '/images/salada-tropical.jpg',
    slug: 'salada-tropical-vinagrete-citrico',
    receitasRelacionadas: ['2', '8', '9', '10'],
    categoriasRelacionadas: ['Saladas', 'Pratos Principais'],
  },
  {
    id: '4',
    titulo: 'Brigadeiro de Café da Lurdinha',
    descricao: 'Meu marido vivia pedindo brigadeiro, mas eu queria dar um giro. Aí acrescentei café bem forte e descobri o doce que os adultos da casa mais amam.',
    categoria: 'Doces',
    tempoPreparo: 10,
    tempoTotal: 30,
    porcoes: 20,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Leite condensado', quantidade: '1 lata (395g)' },
      { item: 'Chocolate em pó premium', quantidade: '4 colheres de sopa' },
      { item: 'Café expresso coado', quantidade: '2 colheres de sopa' },
      { item: 'Manteiga sem sal', quantidade: '2 colheres de sopa' },
      { item: 'Chocolate granulado', quantidade: 'para cobrir' },
      { item: 'Forminhas de papel', quantidade: '20 unidades' },
    ],
    modoPreparo: [
      'Coloque o leite condensado numa panela de fundo grosso. Panela fina queima fácil.',
      'Junte o chocolate em pó e o café bem forte. Mexa até ficar sem gruminhos.',
      'Acrescente a manteiga e leve ao fogo médio, mexendo sem parar.',
      'Cozinhe entre 8 e 10 minutos até o brigadeiro desgrudar do fundo. Aí o ponto está certo.',
      'Despeje num prato untado e espere esfriar completamente.',
      'Unte as mãos e faça bolinhas do tamanho de uma noz.',
      'Passe no granulado e acomode nas forminhas.',
      'Guarde na geladeira em pote fechado para não ressecar.',
    ],
    dicas: [
      'Não pare de mexer, senão o brigadeiro gruda e queima no fundo',
      'Café de coador de pano deixa o sabor mais caseiro e perfumado',
      'Se a massa estiver mole demais, volte ao fogo por mais 2 minutos que ela endurece',
    ],
    imagem: '/images/brigadeiro-cafe.jpg',
    slug: 'brigadeiro-gourmet-cafe',
    receitasRelacionadas: ['15', '17', '19', '20'],
    categoriasRelacionadas: ['Doces', 'Bolos'],
  },
  {
    id: '5',
    titulo: 'Carbonara do jeito que a Lurdinha Aprendeu na Itália',
    descricao: 'Carbonara não leva creme de leite, meu amor. O segredo é o caldo da massa com gema de ovo e queijo, virando um creme dourado no prato.',
    categoria: 'Massas',
    tempoPreparo: 15,
    tempoTotal: 25,
    porcoes: 4,
    dificuldade: 'médio',
    ingredientes: [
      { item: 'Macarrão tipo penne ou spaghetti', quantidade: '400g' },
      { item: 'Bacon fatiado', quantidade: '200g' },
      { item: 'Gema de ovo', quantidade: '3 unidades' },
      { item: 'Queijo parmesão ralado', quantidade: '1 xícara' },
      { item: 'Sal grosso para a água', quantidade: 'a gosto' },
      { item: 'Pimenta preta moída', quantidade: 'a gosto' },
      { item: 'Salsa fresca picada', quantidade: '2 colheres de sopa' },
    ],
    modoPreparo: [
      'Ponha uma panela grande de água com sal grosso para ferver, bem salgada.',
      'Corte o bacon em tirinhas e doure numa frigideira até ficar crocante. Tire e deixe o gordurinha.',
      'Cozinhe o macarrão até ficar al dente, respeitando o tempo do pacote.',
      'Numa tigela, bata as gemas com o queijo parmesão e uma boa dose de pimenta do reino.',
      'Escorra a massa, mas guarde pelo menos 1 xícara da água de cozimento, que é ouro.',
      'Coloque o macarrão quente na frigideira com o bacon e o óleo.',
      'Desligue o fogo. Esse é o truque. Adicione a mistura de gema e queijo, mexendo rápido.',
      'Se o molho estiver grosso, jogue um pouquinho da água da massa até ficar sedoso.',
      'Finalize com salsa e mais pimenta na hora de servir.',
    ],
    dicas: [
      'Só gemas, nunca ovos inteiros, se não vira omelete de macarrão',
      'Desligue o fogo antes de colocar os ovos, senão eles cozinham demais',
      'A água de cozimento com amido é o que dá aquele creme maravilhoso sem creme de leite',
    ],
    imagem: '/images/pasta-carbonara.jpg',
    slug: 'pasta-carbonara-autentica',
    receitasRelacionadas: ['19', '20', '21', '22'],
    categoriasRelacionadas: ['Massas', 'Pratos Principais'],
  },
  {
    id: '6',
    titulo: 'Creme de Abóbora com Gengibre da Lurdinha',
    descricao: 'Nos dias frios, eu faço essa sopa e a casa toda fica com cheiro de aconchego. O gengibre dá aquele esquentadinho na garganta.',
    categoria: 'Sopas',
    tempoPreparo: 20,
    tempoTotal: 40,
    porcoes: 6,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Abóbora madura', quantidade: '1kg' },
      { item: 'Cebola média', quantidade: '1 unidade' },
      { item: 'Gengibre fresco', quantidade: '3 colheres de sopa ralado' },
      { item: 'Alho', quantidade: '2 dentes' },
      { item: 'Caldo de legumes', quantidade: '1 litro' },
      { item: 'Leite de coco', quantidade: '1 xícara' },
      { item: 'Azeite', quantidade: '2 colheres de sopa' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
      { item: 'Cebolinha fresca', quantidade: 'para servir' },
    ],
    modoPreparo: [
      'Descasque a abóbora, tire as sementes e corte em cubos médios. Quanto mais madura, mais doce fica.',
      'Aqueça o azeite numa panela grande e refogue a cebola e o alho até ficarem macios e cheirosos.',
      'Acrescente o gengibre ralado e deixe cozinhar por 1 minutinho, só até o cheiro subir.',
      'Jogue os cubos de abóbora e mexa para envolver no refogado.',
      'Despeje o caldo de legumes e deixe ferver até a abóbora desmanchar com o garfo, cerca de 15 a 20 minutos.',
      'Desligue o fogo e espere amornar um pouco, porque bater sopa quente demais é perigoso.',
      'Bata no liquidificador até virar um creme liso e laranja.',
      'Volte para a panela, coloque o leite de coco e tempere com sal e pimenta.',
      'Aqueça devagar, sem deixar ferver, para não talhar.',
      'Sirva bem quente com cebolinha picadinha por cima.',
    ],
    dicas: [
      'Abóbora madura na banca pesa mais e tem casca mais opaca, dá preferência para essas',
      'Se gostar de sopa mais grossinha, use menos caldo e vá ajustando no final',
      'Congela lindamente em potes pequenos para os dias apressados',
    ],
    imagem: '/images/sopa-abobora-gengibre.jpg',
    slug: 'sopa-abobora-gengibre',
    receitasRelacionadas: ['24', '25', '26', '27'],
    categoriasRelacionadas: ['Sopas', 'Pratos Principais'],
  },
  {
    id: '7',
    titulo: 'Cookies de Aveia com Chocolate que A Lurdinha Faz para os Netos',
    descricao: 'Esses cookies já salvaram muita tarde de chuva aqui em casa. Crocantes por fora, macios por dentro, com gotas de chocolate que derretem na boca.',
    categoria: 'Biscoitos',
    tempoPreparo: 15,
    tempoTotal: 35,
    porcoes: 24,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Manteiga mole', quantidade: '1/2 xícara' },
      { item: 'Açúcar mascavo', quantidade: '3/4 xícara' },
      { item: 'Açúcar branco', quantidade: '1/4 xícara' },
      { item: 'Ovo', quantidade: '1 unidade' },
      { item: 'Extrato de baunilha', quantidade: '1 colher de chá' },
      { item: 'Farinha de trigo', quantidade: '1 xícara' },
      { item: 'Aveia em flocos', quantidade: '1 1/2 xícara' },
      { item: 'Chocolate em gotas', quantidade: '1 xícara' },
      { item: 'Fermento químico', quantidade: '1/2 colher de chá' },
      { item: 'Sal', quantidade: '1/4 colher de chá' },
    ],
    modoPreparo: [
      'Pré-aqueça o forno a 190°C.',
      'Bata a manteiga com o açúcar mascavo e o açúcar branco até virar um creme clarinho.',
      'Acrescente o ovo e a baunilha e bata até ficar homogêneo.',
      'Numa outra tigela, misture a farinha, a aveia, o fermento e o sal.',
      'Junte a mistura seca à úmida, mexendo com uma colher ou espátula, sem batedeira.',
      'Adicione as gotas de chocolate e envolva bem.',
      'Coloque colheradas da massa numa assadeira forrada com papel-manteiga, deixando espaço entre elas.',
      'Asse por 10 a 12 minutos, só até as bordas dourarem. O centro ainda parece mole, mas endurece depois.',
      'Deixe esfriar 5 minutinhos na assadeira, senão eles quebram.',
    ],
    dicas: [
      'Retire do forno quando as bordas estiverem douradas, mesmo que o centro pareça cru',
      'Use gotas de chocolate meio amargo para não ficar enjoativo',
      'Guarde em pote de vidro com tampa para durar a semana toda',
    ],
    imagem: '/images/cookies-aveia-chocolate.jpg',
    slug: 'cookies-aveia-chocolate',
    receitasRelacionadas: ['1', '4', '12', '17'],
    categoriasRelacionadas: ['Biscoitos', 'Doces'],
  },
  {
    id: '8',
    titulo: 'Risoto de Cogumelo que a Lurdinha Faz para impressionar',
    descricao: 'Essa é daquelas receitas que eu tiro quando vem visita em casa. Parece sofisticado, mas o segredo é ir colocando o caldo aos pouquinhos e ter paciência.',
    categoria: 'Pratos Principais',
    tempoPreparo: 25,
    tempoTotal: 40,
    porcoes: 4,
    dificuldade: 'médio',
    ingredientes: [
      { item: 'Arroz arbóreo', quantidade: '1 1/2 xícara' },
      { item: 'Cogumelos variados', quantidade: '400g' },
      { item: 'Cebola pequena', quantidade: '1 unidade' },
      { item: 'Alho', quantidade: '2 dentes' },
      { item: 'Vinho branco seco', quantidade: '1/2 xícara' },
      { item: 'Caldo de legumes quente', quantidade: '1 litro' },
      { item: 'Queijo parmesão ralado', quantidade: '1/2 xícara' },
      { item: 'Manteiga', quantidade: '2 colheres de sopa' },
      { item: 'Azeite', quantidade: '2 colheres de sopa' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
      { item: 'Salsa fresca', quantidade: '1 colher de sopa' },
    ],
    modoPreparo: [
      'Limpe os cogumelos com pano úmido, sem molhar demais, e corte em fatias médias.',
      'Aqueça o azeite e doure os cogumelos em fogo alto. Reserve junto com o líquido deles.',
      'Na mesma panela, derreta a manteiga e refogue a cebola e o alho até ficarem transparentes.',
      'Acrescente o arroz e mexa por 2 minutos, até as bordinhas ficarem brancas.',
      'Despeje o vinho branco e mexa até o álcool sumir e o arroz absorver.',
      'Vá adicionando o caldo quente, uma concha de cada vez, mexendo sempre.',
      'Só coloque mais caldo quando o anterior tiver sido absorvido. Leva uns 18 a 20 minutos.',
      'Quando o arroz estiver al dente, volte os cogumelos e mexa.',
      'Desligue o fogo, junte o restante da manteiga e o parmesão, e mexa até ficar cremoso.',
      'Tempere com sal e pimenta, polvilhe salsa e sirva logo.',
    ],
    dicas: [
      'O caldo precisa estar quente, senão o risoto para de cozinhar direito',
      'Mexer sem parar é que faz o creme aparecer, não esqueça disso',
      'Cogumelos frescos dão sabor de terra muito mais gostoso que o enlatado',
    ],
    imagem: '/images/risoto-cogumelos.jpg',
    slug: 'risoto-cogumelos-selvagens',
    receitasRelacionadas: ['2', '3', '5', '10'],
    categoriasRelacionadas: ['Pratos Principais', 'Massas'],
  },
  {
    id: '9',
    titulo: 'Bowl de Açaí que Parece Foto de Verão',
    descricao: 'Minhas filhas adoram esse café da manhã. É rápido, bonito e dá energia de verdade para começar o dia.',
    categoria: 'Café da Manhã',
    tempoPreparo: 10,
    tempoTotal: 10,
    porcoes: 2,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Polpa de açaí congelada', quantidade: '200g' },
      { item: 'Leite de amêndoa', quantidade: '1/2 xícara' },
      { item: 'Banana congelada', quantidade: '1 unidade' },
      { item: 'Mel puro', quantidade: '1 colher de sopa' },
      { item: 'Granola caseira', quantidade: '1/2 xícara' },
      { item: 'Morango fresco', quantidade: '100g' },
      { item: 'Blueberry', quantidade: '100g' },
      { item: 'Coco ralado', quantidade: '2 colheres de sopa' },
      { item: 'Sementes de chia', quantidade: '1 colher de sopa' },
    ],
    modoPreparo: [
      'No liquidificador, coloque a polpa de açaí, o leite de amêndoa, a banana congelada e o mel.',
      'Bata até ficar cremoso, no ponto de sorvete. Não deixe virar líquido.',
      'Divida em duas tigelas bonitas, porque a gente come com os olhos primeiro.',
      'Salpique granola por cima para dar crocância.',
      'Corte os morangos em fatias e espalhe com os blueberries.',
      'Polvilhe o coco ralado e as sementes de chia no final.',
      'Sirva na hora, antes de derreter.',
    ],
    dicas: [
      'Banana e açaí congelados dão a consistência grossa que faz toda a diferença',
      'Prepare as frutas de cobertura antes de bater o açaí para montar rápido',
      'Sem granola? Use castanhas picadas ou mesmo flocos de aveia torrada',
    ],
    imagem: '/images/smoothie-bowl-acai.jpg',
    slug: 'smoothie-bowl-acai',
    receitasRelacionadas: ['7', '9', '11', '13'],
    categoriasRelacionadas: ['Café da Manhã', 'Doces'],
  },
  {
    id: '10',
    titulo: 'Pão de Fermentação Natural da Lurdinha',
    descricao: 'Esse pão exige paciência, mas o cheiro de casa com pão fresco no forno não tem preço. A crosta estala e o miolo desmancha na boca.',
    categoria: 'Pães',
    tempoPreparo: 30,
    tempoTotal: 480,
    porcoes: 1,
    dificuldade: 'difícil',
    ingredientes: [
      { item: 'Farinha de trigo integral', quantidade: '500g' },
      { item: 'Água filtrada', quantidade: '350ml' },
      { item: 'Fermento natural ativo', quantidade: '100g' },
      { item: 'Sal marinho', quantidade: '10g' },
      { item: 'Azeite', quantidade: '1 colher de sopa' },
    ],
    modoPreparo: [
      'Misture a farinha, água e fermento natural em uma tigela grande.',
      'Deixe descansar por 30 minutos (autólise).',
      'Adicione o sal e o azeite, mexendo bem até incorporar.',
      'Deixe fermentar em temperatura ambiente por 4-6 horas, dobrando a massa a cada 30 minutos.',
      'Coloque a massa em uma superfície enfarinhada e dê forma redonda.',
      'Deixe descansar por 2 horas em um cesto de fermentação ou tigela forrada.',
      'Pré-aqueça o forno a 250°C com uma assadeira dentro.',
      'Vire a massa para a assadeira quente com cuidado.',
      'Faça um corte na superfície com uma faca afiada.',
      'Asse por 35-40 minutos até ficar dourado e soar oco quando batido.',
      'Deixe esfriar completamente antes de cortar.',
    ],
    dicas: [
      'Mantenha o fermento natural alimentado regularmente',
      'A temperatura ambiente afeta o tempo de fermentação',
      'Use água filtrada para melhor resultado',
    ],
    imagem: '/images/pao-fermentacao-natural.jpg',
    slug: 'pao-caseiro-fermentacao-natural',
    receitasRelacionadas: ['7', '9', '11', '13'],
    categoriasRelacionadas: ['Pães', 'Café da Manhã'],
  },
  {
    id: '11',
    titulo: 'Ceviche de Peixe Branco da Lurdinha',
    descricao: 'Essa receita me lembra o verão que passei perto do litoral. Peixe bem fresco, limão e muito coentro. Simples, mas perfeito.',
    categoria: 'Frutos do Mar',
    tempoPreparo: 20,
    tempoTotal: 30,
    porcoes: 4,
    dificuldade: 'médio',
    ingredientes: [
      { item: 'Peixe branco fresco', quantidade: '600g' },
      { item: 'Suco de limão fresco', quantidade: '1 xícara' },
      { item: 'Cebola roxa', quantidade: '1 unidade' },
      { item: 'Pimenta vermelha', quantidade: '1 unidade' },
      { item: 'Coentro fresco', quantidade: '1/4 xícara' },
      { item: 'Sal marinho', quantidade: 'a gosto' },
      { item: 'Pimenta preta', quantidade: 'a gosto' },
      { item: 'Batata doce', quantidade: '2 unidades' },
      { item: 'Milho cozido', quantidade: '1 xícara' },
    ],
    modoPreparo: [
      'Corte o peixe em cubinhos pequenos e do mesmo tamanho para cozinhar uniformemente.',
      'Coloque o peixe numa tigela de vidro e cubra com o suco de limão. Ele precisa estar bem coberto.',
      'Leve à geladeira por 15 a 20 minutos. O peixe vai ficar opaco, esse é o sinal de que está bom.',
      'Enquanto isso, corte a cebola em meias-luas bem fininhas.',
      'Tire as sementes da pimenta e corte em tirinhas.',
      'Pique bastante coentro, eu gosto de colocar sem moderação.',
      'Cozinhe a batata doce até ficar macia e corte em rodelas para acompanhar.',
      'Retire o peixe da marinada e coloque numa tigela.',
      'Junte a cebola, a pimenta, o coentro, o sal e a pimenta preta. Misture com cuidado.',
      'Sirva em taças com as rodelas de batata doce e o milho ao lado.',
    ],
    dicas: [
      'Peixe do dia, bem fresco, é a única opção para ceviche. Não arrisque peixe velho.',
      'O limão cozinha o peixe sem fogo, por isso o tempo importa. Mais de 20 minutos pode deixar borrachudo.',
      'Se não gostar de ardência, tire as sementes da pimenta e use só um pedacinho.',
    ],
    imagem: '/images/ceviche-peruano.jpg',
    slug: 'ceviche-peruano-tradicional',
    receitasRelacionadas: ['2', '8', '9', '10'],
    categoriasRelacionadas: ['Frutos do Mar', 'Pratos Principais'],
  },
  {
    id: '12',
    titulo: 'Torta de Maçã com Canela que Cheira a Infância',
    descricao: 'Minha mãe fazia uma torta de maçã parecida com essa. O cheiro de canela tomava a casa e eu já sabia que algo bom saía do forno.',
    categoria: 'Bolos',
    tempoPreparo: 25,
    tempoTotal: 50,
    porcoes: 8,
    dificuldade: 'médio',
    ingredientes: [
      { item: 'Massa folhada pronta', quantidade: '500g' },
      { item: 'Maçã verde', quantidade: '4 unidades' },
      { item: 'Açúcar cristal', quantidade: '1/2 xícara' },
      { item: 'Canela em pó', quantidade: '2 colheres de chá' },
      { item: 'Suco de limão', quantidade: '2 colheres de sopa' },
      { item: 'Manteiga', quantidade: '3 colheres de sopa' },
      { item: 'Farinha de trigo', quantidade: '1 colher de sopa' },
      { item: 'Gema de ovo', quantidade: '1 unidade' },
      { item: 'Água', quantidade: '1 colher de sopa' },
    ],
    modoPreparo: [
      'Pré-aqueça o forno a 200°C.',
      'Descasque as maçãs, retire o miolo e corte em fatias finas.',
      'Coloque numa tigela com o suco de limão para não escurecer.',
      'Derreta a manteiga numa frigideira, acrescente o açúcar e a canela.',
      'Coloque as maçãs e cozinhe por 5 a 7 minutos até caramelizar. Mexa de vez em quando.',
      'Desligue e deixe esfriar um pouco, senão queima a massa.',
      'Forre uma forma de torta com a massa folhada.',
      'Polvilhe a farinha no fundo para não encharcar.',
      'Distribua as maçãs caramelizadas sobre a massa.',
      'Dobre as bordas da massa sobre o recheio, sem pressa.',
      'Bata a gema com a água e pincele sobre a massa.',
      'Asse por 25 a 30 minutos até a massa ficar dourada e crocante.',
      'Espere amornar antes de cortar, aí os pedaços saem inteiros.',
    ],
    dicas: [
      'Maçã verde é a melhor escolha, equilibra o doce com a acidez',
      'A caramelização traz o sabor de torta de padaria, não pule',
      'Sirva morna com uma bola de sorvete de baunilha que derrete por cima',
    ],
    imagem: '/images/torta-maca-canela.jpg',
    slug: 'torta-maca-canela',
    receitasRelacionadas: ['1', '4', '7', '12'],
    categoriasRelacionadas: ['Bolos', 'Doces'],
  },
  {
    id: '13',
    titulo: 'Tacos de Carnitas da Lurdinha para Reunição de Amigos',
    descricao: 'Sábado com amigos pede comida que dá para comer com as mãos. As carnitas desmancham na boca e as tortilhas quentes fazem a festa.',
    categoria: 'Pratos Principais',
    tempoPreparo: 30,
    tempoTotal: 180,
    porcoes: 6,
    dificuldade: 'médio',
    ingredientes: [
      { item: 'Paleta de porco', quantidade: '1kg' },
      { item: 'Laranja', quantidade: '2 unidades' },
      { item: 'Limão', quantidade: '2 unidades' },
      { item: 'Alho', quantidade: '6 dentes' },
      { item: 'Cominho em grão', quantidade: '1 colher de chá' },
      { item: 'Orégano seco', quantidade: '1 colher de chá' },
      { item: 'Louro', quantidade: '2 folhas' },
      { item: 'Sal grosso', quantidade: 'a gosto' },
      { item: 'Pimenta preta', quantidade: 'a gosto' },
      { item: 'Tortilhas de milho', quantidade: '12 unidades' },
      { item: 'Cebola roxa', quantidade: '1 unidade' },
      { item: 'Coentro fresco', quantidade: 'para servir' },
    ],
    modoPreparo: [
      'Corte a paleta de porco em cubos grandes, tipo pedaços de estrogonofe.',
      'Esprema o suco das laranjas e limões numa tigela.',
      'Numa panela grande, coloque a carne, os sucos cítricos, o alho em casca, o cominho, o orégano, o louro, o sal e a pimenta.',
      'Leve para ferver, depois abaixe o fogo e deixe cozinhar devagar.',
      'Cozinhe por 2 a 3 horas, até a carne desfiar com um garfo. O cheiro vai tomar a casa.',
      'Retire a carne do caldo e espere amornar.',
      'Desfie com dois garfos, ela desmancha sozinha.',
      'Ponha a carne numa frigideira com um pouco do caldo de cozimento.',
      'Deixe dourar em fogo alto até formar uma casquinha crocante nas bordas.',
      'Aqueça as tortilhas numa frigideira ou sobre o fogo bem de pertinho.',
      'Monte os tacos com a carne, cebola roxa e coentro generoso.',
    ],
    dicas: [
      'Se a carne não desfiar fácil, ainda não cozinhou o suficiente. Mais tempo é melhor.',
      'Guarda o caldo do cozimento, é ouro para molhar a carne depois',
      'Sirva com limão, salsa e guacamole para cada um montar do jeito que gosta',
    ],
    imagem: '/images/tacos-carnitas.jpg',
    slug: 'tacos-carnitas-mexicanos',
    receitasRelacionadas: ['2', '3', '8', '10'],
    categoriasRelacionadas: ['Pratos Principais', 'Carnes'],
  },
  {
    id: '14',
    titulo: 'Quiche de Brócolis que a Lurdinha Leva nas Reuniões de Família',
    descricao: 'Essa quiche é fácil de levar e nunca sobra. Brócolis, queijo e massa crocante fazem uma combinação que agradou até quem dizia não gostar de verdura.',
    categoria: 'Pratos Principais',
    tempoPreparo: 20,
    tempoTotal: 50,
    porcoes: 6,
    dificuldade: 'médio',
    ingredientes: [
      { item: 'Massa de torta pronta', quantidade: '1 unidade' },
      { item: 'Brócolis fresco', quantidade: '300g' },
      { item: 'Queijo cheddar ralado', quantidade: '1 xícara' },
      { item: 'Ovos', quantidade: '3 unidades' },
      { item: 'Leite integral', quantidade: '1 xícara' },
      { item: 'Cebola pequena', quantidade: '1 unidade' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
      { item: 'Noz-moscada', quantidade: '1/4 colher de chá' },
      { item: 'Manteiga', quantidade: '1 colher de sopa' },
    ],
    modoPreparo: [
      'Pré-aqueça o forno a 190°C.',
      'Forre uma forma de 25cm com a massa de torta e fure o fundo com um garfo para não encher de ar.',
      'Separe o brócolis em floretes pequenos.',
      'Cozinhe o brócolis em água com sal por 3 a 4 minutos, só até ficar verde e crocante. Escorra bem.',
      'Pique a cebola bem miudinha e refogue na manteiga até ficar transparente.',
      'Numa tigela, bata os ovos com o leite, sal, pimenta e uma pitada de noz-moscada.',
      'Espalhe o brócolis e a cebola sobre a massa.',
      'Salpique o queijo cheddar por cima.',
      'Despeje o creme de ovos com cuidado para não bagunçar os ingredientes.',
      'Asse por 30 a 35 minutos, até dourar e o centro firmar.',
      'Deixe descansar 10 minutinhos antes de cortar, aí sai perfeito.',
    ],
    dicas: [
      'Cozinhe o brócolis al dente, porque ele termina de cozinhar no forno',
      'Pode montar de véspera e assar só na hora de servir',
      'Troque o cheddar por mussarela ou queijo minas ralado que fica mais leve',
    ],
    imagem: '/images/quiche-brocolis-queijo.jpg',
    slug: 'quiche-brocolis-queijo',
    receitasRelacionadas: ['9', '18', '19', '20'],
    categoriasRelacionadas: ['Pratos Principais', 'Café da Manhã'],
  },
  {
    id: '15',
    titulo: 'Pudim de Leite Condensado da Lurdinha',
    descricao: 'Todo domingo na minha casa tinha pudim. Esse é o clássico, lisinho, com calda que escorre lenta e faz a gente querer lambuzar o prato.',
    categoria: 'Doces',
    tempoPreparo: 15,
    tempoTotal: 240,
    porcoes: 8,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Leite condensado', quantidade: '1 lata (395g)' },
      { item: 'Leite integral', quantidade: '1 lata (200ml)' },
      { item: 'Ovos', quantidade: '4 unidades' },
      { item: 'Açúcar para caramelo', quantidade: '1 xícara' },
      { item: 'Água', quantidade: '1/2 xícara' },
    ],
    modoPreparo: [
      'Pré-aqueça o forno a 180°C.',
      'Unte uma forma redonda de 20cm com caramelo depois que estiver pronto.',
      'Numa panela, coloque o açúcar e a água para o caramelo.',
      'Cozinhe em fogo médio até ficar dourado claro. Não mexa, só incline a panela.',
      'Despeje o caramelo quente na forma, girando para cobrir o fundo e as laterais.',
      'No liquidificador, bata o leite condensado, o leite e os ovos por 2 a 3 minutos, até ficar liso.',
      'Despeje a mistura sobre o caramelo na forma.',
      'Coloque a forma dentro de uma assadeira com água quente até a metade.',
      'Asse por 50 a 60 minutos. O centro ainda pode tremer um pouco, é normal.',
      'Deixe esfriar e leve à geladeira por no mínimo 4 horas, de um dia para o outro é melhor.',
      'Para desenformar, passe uma faca na borda e vire com cuidado sobre um prato.',
    ],
    dicas: [
      'Pudim continua cozinhando depois do forno, então tire um pouco antes de ficar duro',
      'A calda é o coração da receita, não tenha medo do caramelo',
      'Faço de véspera sempre que vou receber gente, pois fica melhor descansado',
    ],
    imagem: '/images/pudim-leite-condensado.jpg',
    slug: 'pudim-leite-condensado',
    receitasRelacionadas: ['4', '12', '17', '21'],
    categoriasRelacionadas: ['Doces', 'Sobremesas'],
  },
  {
    id: '16',
    titulo: 'Bife com Molho de Vinho que a Lurdinha Faz em Jantar Especial',
    descricao: 'Jantar romântico ou aniversário aqui em casa pede esse prato. A carna selada e o molho de vinho deixam todo mundo achando que eu sou chef.',
    categoria: 'Pratos Principais',
    tempoPreparo: 20,
    tempoTotal: 35,
    porcoes: 2,
    dificuldade: 'médio',
    ingredientes: [
      { item: 'Bife ancho', quantidade: '2 unidades (300g cada)' },
      { item: 'Vinho tinto seco', quantidade: '1 xícara' },
      { item: 'Caldo de carne', quantidade: '1 xícara' },
      { item: 'Manteiga', quantidade: '3 colheres de sopa' },
      { item: 'Alho', quantidade: '3 dentes' },
      { item: 'Tomilho fresco', quantidade: '2 ramos' },
      { item: 'Sal grosso', quantidade: 'a gosto' },
      { item: 'Pimenta preta moída', quantidade: 'a gosto' },
      { item: 'Azeite', quantidade: '2 colheres de sopa' },
    ],
    modoPreparo: [
      'Tire os bifes da geladeira 30 minutos antes, a carne não pode ir ao fogo gelada.',
      'Tempere bem com sal grosso e pimenta do reino moída na hora.',
      'Aqueça o azeite numa frigideira de ferro até quase fumegar.',
      'Coloque os bifes e doure 4 a 5 minutos de cada lado para ponto médio.',
      'Retire a carne e deixe descansar num prato, coberto com papel-alumínio.',
      'Na mesma frigideira, coloque o alho e o tomilho e refogue por 1 minuto.',
      'Despeje o vinho tinto e deixe reduzir pela metade, uns 3 a 4 minutos.',
      'Adicione o caldo de carne e reduza novamente até o molho ficar cremoso.',
      'Desligue o fogo e vá acrescentando a manteiga em cubinhos, mexendo.',
      'Sirva o bife regado com o molho por cima.',
    ],
    dicas: [
      'Vire a carne só uma vez, assim ela doura e não perde o caldo',
      'Termômetro ajuda: 55°C para mal-passado, 60°C para o ponto médio',
      'Descansar a carne depois de grelhar é sagrado, senão o suco escorre todo',
    ],
    imagem: '/images/steak-molho-vinho.jpg',
    slug: 'steak-molho-vinho-tinto',
    receitasRelacionadas: ['2', '3', '8', '13'],
    categoriasRelacionadas: ['Pratos Principais', 'Carnes'],
  },
  {
    id: '17',
    titulo: 'Pavê de Chocolate da Lurdinha para Sofrer de Gostoso',
    descricao: 'Essa é minha versão do clássico pavê de chocolate. Camadas de biscoito de polvilho, creme de chocolate e uma cobertura que dá vontade de passar o dedo na travessa.',
    categoria: 'Doces',
    tempoPreparo: 30,
    tempoTotal: 300,
    porcoes: 10,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Biscoito de polvilho', quantidade: '400g' },
      { item: 'Leite integral', quantidade: '1 xícara' },
      { item: 'Chocolate em pó', quantidade: '1/2 xícara' },
      { item: 'Açúcar', quantidade: '1/2 xícara' },
      { item: 'Gema de ovo', quantidade: '3 unidades' },
      { item: 'Manteiga mole', quantidade: '1/2 xícara' },
      { item: 'Leite condensado', quantidade: '1 lata (395g)' },
      { item: 'Chocolate em gotas', quantidade: '1 xícara' },
      { item: 'Café coado', quantidade: '1/2 xícara' },
    ],
    modoPreparo: [
      'Use uma forma retangular de 25x35cm.',
      'Misture o café coado com um pouco de água morna.',
      'Mergulhe rapidamente cada biscoito no café e faça uma camada na forma.',
      'Numa panela, leve a manteiga, o açúcar e as gemas em banho-maria, mexendo até virar creme.',
      'Retire e deixe esfriar um pouco para não derreter o leite condensado.',
      'Acrescente o leite condensado e misture bem.',
      'Espalhe metade do creme sobre o biscoito.',
      'Faça mais uma camada de biscoito molhado.',
      'Cobre com o restante do creme.',
      'Finalize com outra camada de biscoito.',
      'Derreta as gotas de chocolate com o leite e espalhe por cima.',
      'Leve à geladeira por pelo menos 4 horas, de um dia para o outro fica melhor.',
    ],
    dicas: [
      'Molhe o biscoito de polvilho bem rápido, senão desmancha',
      'Pavê ganha sabor quando descansa na geladeira de um dia para o outro',
      'Pode ser feito com 2 dias de antecedência que só melhora',
    ],
    imagem: '/images/pave-chocolate.jpg',
    slug: 'pave-chocolate',
    receitasRelacionadas: ['1', '4', '12', '15'],
    categoriasRelacionadas: ['Doces', 'Sobremesas'],
  },
  {
    id: '18',
    titulo: 'Frittata de Legumes para o Café da Lurdinha',
    descricao: 'Quando abro a geladeira e vejo sobrinhas de legumes, já sei que vai virar frittata. É fácil, linda e dá para alimentar a família sem desperdiçar nada.',
    categoria: 'Café da Manhã',
    tempoPreparo: 15,
    tempoTotal: 25,
    porcoes: 4,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Ovos', quantidade: '8 unidades' },
      { item: 'Pimentão vermelho', quantidade: '1 unidade' },
      { item: 'Cebola pequena', quantidade: '1 unidade' },
      { item: 'Espinafre fresco', quantidade: '2 xícaras' },
      { item: 'Queijo mozzarela ralado', quantidade: '1 xícara' },
      { item: 'Azeite', quantidade: '2 colheres de sopa' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
      { item: 'Orégano seco', quantidade: '1/2 colher de chá' },
    ],
    modoPreparo: [
      'Pré-aqueça o forno a 190°C.',
      'Corte o pimentão e a cebola em cubinhos.',
      'Aqueça o azeite numa frigideira antiaderente e refogue a cebola e o pimentão por 3 minutos.',
      'Acrescente o espinafre e deixe murchar, cerca de 2 minutos.',
      'Bata os ovos com sal, pimenta e orégano.',
      'Despeje os ovos por cima dos legumes, espalhando bem.',
      'Cozinhe em fogo médio até as bordas começarem a firmar.',
      'Polvilhe a mussarela por cima.',
      'Leve ao forno por 8 a 10 minutos até dourar e firmar no centro.',
      'Espere amornar, corte em fatias e sirva.',
    ],
    dicas: [
      'Frigideira de cabo de metal ou de ferro é ideal para levar ao forno',
      'Essa receita aceita todo tipo de sobra: abobrinha, tomate, cenoura, o que tiver',
      'Fica ótima fria no dia seguinte, perfeita para lanche da tarde',
    ],
    imagem: '/images/frittata-vegetais.jpg',
    slug: 'frittata-vegetais',
    receitasRelacionadas: ['3', '9', '14', '18'],
    categoriasRelacionadas: ['Café da Manhã', 'Pratos Principais'],
  },
  {
    id: '19',
    titulo: 'Pesto Caseiro do Quintal da Lurdinha',
    descricao: 'Quando o pé de manjericão dá aquele estouro no meu quintal, eu faço pesto. É fresco, perfumado e transforma até o macarrão mais simples em jantar de sábado.',
    categoria: 'Molhos',
    tempoPreparo: 10,
    tempoTotal: 10,
    porcoes: 8,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Folhas de manjericão fresco', quantidade: '2 xícaras' },
      { item: 'Alho', quantidade: '3 dentes' },
      { item: 'Pinhão', quantidade: '1/2 xícara' },
      { item: 'Queijo parmesão ralado', quantidade: '1/2 xícara' },
      { item: 'Azeite extra virgem', quantidade: '3/4 xícara' },
      { item: 'Suco de limão', quantidade: '1 colher de sopa' },
      { item: 'Sal marinho', quantidade: 'a gosto' },
      { item: 'Pimenta preta', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Coloque no processador o manjericão, o alho e os pinhões.',
      'Pulse até ficar picado, mas ainda com textura.',
      'Adicione o parmesão e pulse mais um pouco.',
      'Com o processador ligado, vá colocando o azeite num fio até o pesto ficar cremoso.',
      'Tempere com o suco de limão, sal e pimenta.',
      'Pulse mais uma vez para misturar tudo.',
      'Passe para um pote de vidro.',
      'Para conservar, cubra com uma camada fina de azeite.',
    ],
    dicas: [
      'Manjericão fresco, sem manchas escuras, é o segredo do pesto verde e saboroso',
      'Não leve o pesto ao fogo, ele perde a cor e o sabor. Misture só no final',
      'Dura até uma semana na geladeira se estiver bem coberto de azeite',
    ],
    imagem: '/images/molho-pesto.jpg',
    slug: 'molho-pesto-caseiro',
    receitasRelacionadas: ['5', '8', '10', '11'],
    categoriasRelacionadas: ['Molhos', 'Pratos Principais'],
  },
  {
    id: '20',
    titulo: 'Soufflé de Queijo que a Lurdinha Só Faz em Ocasiao Especial',
    descricao: 'Soufflé é daqueles pratos que parecem difíceis, mas são só questão de técnica. Quando sai dourado e altinho do forno, dá uma sensação de conquista.',
    categoria: 'Pratos Principais',
    tempoPreparo: 20,
    tempoTotal: 35,
    porcoes: 4,
    dificuldade: 'difícil',
    ingredientes: [
      { item: 'Manteiga', quantidade: '3 colheres de sopa' },
      { item: 'Farinha de trigo', quantidade: '3 colheres de sopa' },
      { item: 'Leite integral', quantidade: '1 xícara' },
      { item: 'Queijo gruyère ralado', quantidade: '1 xícara' },
      { item: 'Gema de ovo', quantidade: '4 unidades' },
      { item: 'Claras de ovo', quantidade: '5 unidades' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
      { item: 'Noz-moscada', quantidade: '1/4 colher de chá' },
      { item: 'Manteiga para untar', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Pré-aqueça o forno a 200°C.',
      'Unte bem 4 ramequins com manteiga e polvilhe farinha, retirando o excesso.',
      'Numa panela, derreta a manteiga em fogo médio.',
      'Acrescente a farinha e mexa por 1 minuto para formar o roux.',
      'Adicione o leite aos poucos, mexendo sempre, até o creme ficar liso.',
      'Cozinhe por 2 a 3 minutos até engrossar.',
      'Retire do fogo e misture o queijo, sal, pimenta e noz-moscada.',
      'Deixe amornar e acrescente as gemas uma a uma, mexendo bem.',
      'Bata as claras em neve firme, numa tigela limpa e seca.',
      'Incorpore as claras à mistura de queijo em três vezes, com movimentos suaves.',
      'Distribua nos ramequins.',
      'Asse por 15 a 20 minutos, até dourar e firmar nas laterais, mas ainda com o centro levemente mole.',
      'Sirva logo, antes que abaixe.',
    ],
    dicas: [
      'Não abra o forno durante o cozimento, senão o soufflé desmorona',
      'Claras em neve bem firme são o que fazem o soufflé crescer alto',
      'Leve imediatamente à mesa, pois o espetáculo dura poucos minutos',
    ],
    imagem: '/images/souffle-queijo.jpg',
    slug: 'souffle-queijo',
    receitasRelacionadas: ['14', '18', '9', '13'],
    categoriasRelacionadas: ['Pratos Principais', 'Café da Manhã'],
  },
  {
    id: '21',
    titulo: 'Bolo no Pote da Lurdinha',
    descricao: 'Bolinhos individuais de chocolate com recheio cremoso que fazem sucesso na hora de vender ou presentear',
    categoria: 'Bolos',
    tempoPreparo: 25,
    tempoTotal: 55,
    porcoes: 6,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Farinha de trigo', quantidade: '1 1/2 xícara' },
      { item: 'Açúcar', quantidade: '1 xícara' },
      { item: 'Ovos', quantidade: '2 unidades' },
      { item: 'Leite', quantidade: '1/2 xícara' },
      { item: 'Óleo', quantidade: '1/3 xícara' },
      { item: 'Chocolate em pó', quantidade: '1/2 xícara' },
      { item: 'Fermento em pó', quantidade: '1 colher de sopa' },
      { item: 'Leite condensado', quantidade: '1 lata' },
      { item: 'Creme de leite', quantidade: '1/2 lata' },
      { item: 'Chocolate meio amargo', quantidade: '200g' },
      { item: 'Granulado', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Pré-aqueça o forno a 180°C.',
      'Em uma tigela, misture a farinha, o açúcar, o chocolate em pó e o fermento.',
      'Adicione os ovos, o leite e o óleo, batendo até ficar homogêneo.',
      'Despeje a massa em potinhos de vidro individuais até dois terços da altura.',
      'Asse por 25 a 30 minutos ou até o palito sair limpo.',
      'Deixe os bolinhos esfriar completamente.',
      'Prepare a cobertura: leve o leite condensado, creme de leite e chocolate ao fogo baixo até derreter e engrossar.',
      'Faça um buraco no centro de cada bolo e recheie com parte da cobertura.',
      'Cubra com a cobertura restante e decore com granulado.',
      'Sirva em seguida ou guarde na geladeira por até 3 dias.',
    ],
    dicas: [
      'Use potinhos de vidro ou plástico próprios para alimentos',
      'Cobertura fica melhor quando esfria um pouco antes de usar',
      'Esses bolos são ótimos para vender ou levar em encontros',
    ],
    imagem: '/images/bolo-no-pote.jpg',
    slug: 'bolo-no-pote-lurdinha',
    receitasRelacionadas: ['1', '4', '12', '15'],
    categoriasRelacionadas: ['Bolos', 'Doces'],
  },
  {
    id: '22',
    titulo: 'Pudim de Leite da Lurdinha',
    descricao: 'Pudim lisinho, sem furinhos, com calda de caramelo feita na pressão certa para não amargar',
    categoria: 'Doces',
    tempoPreparo: 15,
    tempoTotal: 90,
    porcoes: 8,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Açúcar', quantidade: '1 1/2 xícara' },
      { item: 'Ovos', quantidade: '4 unidades' },
      { item: 'Leite condensado', quantidade: '1 lata' },
      { item: 'Leite integral', quantidade: '2 medidas da lata de leite condensado' },
      { item: 'Baunilha', quantidade: '1 colher de chá' },
    ],
    modoPreparo: [
      'Derreta o açúcar em fogo médio até formar um caramelo dourado.',
      'Despeje o caramelo na forma de pudim, espalhando pelo fundo.',
      'No liquidificador, bata os ovos, o leite condensado, o leite e a baunilha por 3 minutos.',
      'Despeje a mistura na forma caramelizada.',
      'Asse em banho-maria a 180°C por 50 a 60 minutos.',
      'Espete um palito: deve sair levemente úmido.',
      'Deixe esfriar e leve à geladeira por no mínimo 4 horas.',
      'Para desenformar, passe uma faca nas bordas e vire sobre um prato.',
    ],
    dicas: [
      'Não deixe o caramelo escurecer demais para não amargar',
      'Bater a mistura direitinho evita furinhos no pudim',
      'O pudim fica melhor no dia seguinte',
    ],
    imagem: '/images/pudim-leite.jpg',
    slug: 'pudim-leite-lurdinha',
    receitasRelacionadas: ['15', '17', '23', '4'],
    categoriasRelacionadas: ['Doces', 'Sobremesas'],
  },
  {
    id: '23',
    titulo: 'Pavê de Bolacha Mais Cremoso do Mundo',
    descricao: 'Camadas de bolacha molhada em café, creme de chocolate e chantilly que lembram os domingos na casa da minha avó',
    categoria: 'Doces',
    tempoPreparo: 30,
    tempoTotal: 240,
    porcoes: 12,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Bolacha tipo maisena', quantidade: '1 pacote' },
      { item: 'Café coado forte', quantidade: '2 xícaras' },
      { item: 'Leite condensado', quantidade: '1 lata' },
      { item: 'Leite integral', quantidade: '2 xícaras' },
      { item: 'Gemas', quantidade: '4 unidades' },
      { item: 'Amido de milho', quantidade: '3 colheres de sopa' },
      { item: 'Chocolate em pó', quantidade: '4 colheres de sopa' },
      { item: 'Creme de leite', quantidade: '1 lata' },
      { item: 'Chantilly pronto', quantidade: '1 pote' },
      { item: 'Chocolate granulado', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Prepare o creme: leve ao fogo o leite condensado, o leite, as gemas, o amido, o chocolate em pó e o creme de leite.',
      'Mexa sem parar até engrossar e formar um creme liso.',
      'Deixe o creme esfriar, cobrindo com plástico em contato.',
      'Misture o café com um pouco de água morna para molhar a bolacha.',
      'Em um refratário, faça uma camada de bolachas molhadas.',
      'Cubra com uma camada de creme.',
      'Repita as camadas até acabar os ingredientes, finalizando com creme.',
      'Cubra com chantilly e granulado.',
      'Leve à geladeira por pelo menos 4 horas, melhor de um dia para o outro.',
    ],
    dicas: [
      'Molhe a bolacha rapidamente para não derreter',
      'O pavê fica melhor quando os sabores se integram de um dia para o outro',
      'Pode substituir o chantilly por clara em neve se preferir',
    ],
    imagem: '/images/pave-bolacha.jpg',
    slug: 'pave-bolacha-cremoso',
    receitasRelacionadas: ['17', '15', '21', '4'],
    categoriasRelacionadas: ['Doces', 'Sobremesas'],
  },
  {
    id: '24',
    titulo: 'Bolo de Milho Cremoso de Liquidificador',
    descricao: 'Bolo de milho fofinho e úmido que sai do liquidificador direto para o forno, perfeito para o café da tarde',
    categoria: 'Bolos',
    tempoPreparo: 10,
    tempoTotal: 50,
    porcoes: 10,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Milho verde', quantidade: '2 xícaras' },
      { item: 'Ovos', quantidade: '3 unidades' },
      { item: 'Açúcar', quantidade: '1 xícara' },
      { item: 'Manteiga derretida', quantidade: '1/2 xícara' },
      { item: 'Leite', quantidade: '1 xícara' },
      { item: 'Fubá', quantidade: '1 xícara' },
      { item: 'Farinha de trigo', quantidade: '1/2 xícara' },
      { item: 'Fermento em pó', quantidade: '1 colher de sopa' },
      { item: 'Erva-doce', quantidade: '1 colher de chá' },
    ],
    modoPreparo: [
      'Pré-aqueça o forno a 180°C e unte uma forma retangular.',
      'No liquidificador, bata o milho, os ovos, o açúcar, a manteiga e o leite.',
      'Adicione o fubá, a farinha, o fermento e a erva-doce e bata rapidamente para misturar.',
      'Despeje a massa na forma.',
      'Asse por 40 a 45 minutos até dourar e o palito sair limpo.',
      'Deixe esfriar um pouco antes de cortar em quadrados.',
    ],
    dicas: [
      'Use milho verde fresco para sabor mais intenso',
      'Pode adicionar coco ralado se gostar',
      'Fica ótimo acompanhado de café com leite',
    ],
    imagem: '/images/bolo-milho.jpg',
    slug: 'bolo-milho-cremoso',
    receitasRelacionadas: ['1', '12', '21', '9'],
    categoriasRelacionadas: ['Bolos', 'Café da Manhã'],
  },
  {
    id: '25',
    titulo: 'Cuscuz Recheado de Carne do Sertão',
    descricao: 'Cuscuz nordestino recheado com carne seca desfiada, uma receita que meu pai fazia nos domingos',
    categoria: 'Pratos Principais',
    tempoPreparo: 30,
    tempoTotal: 60,
    porcoes: 4,
    dificuldade: 'médio',
    ingredientes: [
      { item: 'Flocão de milho', quantidade: '2 xícaras' },
      { item: 'Água morna', quantidade: '2 xícaras' },
      { item: 'Sal', quantidade: '1 colher de chá' },
      { item: 'Carne seca dessalgada e cozida', quantidade: '300g' },
      { item: 'Cebola picada', quantidade: '1 unidade' },
      { item: 'Tomate picado', quantidade: '2 unidades' },
      { item: 'Coentro', quantidade: 'a gosto' },
      { item: 'Azeite', quantidade: '2 colheres de sopa' },
      { item: 'Manteiga', quantidade: '1 colher de sopa' },
    ],
    modoPreparo: [
      'Hidrate o flocão com água morna e sal, deixando descansar 10 minutos.',
      'Refogue a cebola no azeite até dourar.',
      'Adicione o tomate e a carne seca desfiada, cozinhe por 5 minutos.',
      'Finalize com coentro e reserve.',
      'Forre o fundo de uma cuscuzeira com uma parte do flocão hidratado.',
      'Coloque o recheio de carne seca no centro.',
      'Cubra com o restante do flocão.',
      'Leve ao fogo para cozinhar no vapor por 20 a 25 minutos.',
      'Sirva quente com manteiga por cima.',
    ],
    dicas: [
      'A carne seca precisa ser bem dessalgada antes de usar',
      'Não amasse o cuscuz para ele ficar soltinho',
      'Bom a qualquer hora do dia, do café da manhã ao jantar',
    ],
    imagem: '/images/cuscuz-recheado.jpg',
    slug: 'cuscuz-recheado-carne',
    receitasRelacionadas: ['2', '13', '26', '10'],
    categoriasRelacionadas: ['Pratos Principais', 'Carnes'],
  },
  {
    id: '26',
    titulo: 'Feijoada da Lurdinha Sem Complicação',
    descricao: 'Feijoada caseira e cheia de sabor, feita no dia a dia sem precisar de ocasião especial',
    categoria: 'Pratos Principais',
    tempoPreparo: 30,
    tempoTotal: 120,
    porcoes: 6,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Feijão preto', quantidade: '500g' },
      { item: 'Linguiça calabresa', quantidade: '300g' },
      { item: 'Paio', quantidade: '200g' },
      { item: 'Costela de porco', quantidade: '400g' },
      { item: 'Bacon em cubos', quantidade: '100g' },
      { item: 'Alho', quantidade: '4 dentes' },
      { item: 'Cebola', quantidade: '1 unidade' },
      { item: 'Folhas de louro', quantidade: '2 unidades' },
      { item: 'Laranja', quantidade: '1 unidade' },
      { item: 'Azeite', quantidade: '2 colheres de sopa' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Deixe o feijão de molho por 8 horas e escorra.',
      'Cozinhe o feijão com água e o lombo de ouro ou costela até começar a ficar macio.',
      'Em outra panela, refogue o alho, a cebola, o bacon e as linguiças.',
      'Adicione o feijão cozido com um pouco do caldo para a panela de temperos.',
      'Cozinhe por mais 40 minutos em fogo baixo.',
      'Adicione as folhas de louro e a laranja cortada em rodelas.',
      'Ajuste o sal e a pimenta.',
      'Sirva com arroz branco, couve refogada e farofa.',
    ],
    dicas: [
      'O laranja ajuda a cortar o enjoo do feijão',
      'Ferva o feijão sem tampa para não escurecer',
      'Sobra de feijoada congela muito bem',
    ],
    imagem: '/images/feijoada-lurdinha.jpg',
    slug: 'feijoada-lurdinha',
    receitasRelacionadas: ['25', '2', '13', '16'],
    categoriasRelacionadas: ['Pratos Principais', 'Carnes'],
  },
  {
    id: '27',
    titulo: 'Patê de Frango com Cenoura',
    descricao: 'Patê cremoso de frango desfiado com cenoura ralada que serve de acompanhamento, recheio e até lanche',
    categoria: 'Acompanhamentos',
    tempoPreparo: 15,
    tempoTotal: 30,
    porcoes: 6,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Peito de frango cozido e desfiado', quantidade: '2 xícaras' },
      { item: 'Cenoura ralada fina', quantidade: '1/2 xícara' },
      { item: 'Maionese', quantidade: '1/2 xícara' },
      { item: 'Creme de leite', quantidade: '1/4 de xícara' },
      { item: 'Azeite', quantidade: '1 colher de sopa' },
      { item: 'Alho picado', quantidade: '1 dente' },
      { item: 'Salsinha picada', quantidade: '2 colheres de sopa' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Refogue o alho no azeite até dourar levemente.',
      'Adicione o frango desfiado e a cenoura, misture bem.',
      'Cozinhe por 3 minutos para secar o excesso de líquido.',
      'Retire do fogo e deixe esfriar.',
      'Misture a maionese, o creme de leite e a salsinha.',
      'Tempere com sal e pimenta.',
      'Leve à geladeira por 30 minutos antes de servir.',
      'Sirva com torradas, crackers ou como recheio de pão de forma.',
    ],
    dicas: [
      'Use frango bem temperado para mais sabor',
      'Rale a cenoura fina para não ficar dura no patê',
      'Dura até 3 dias na geladeira se bem fechado',
    ],
    imagem: '/images/pate-frango.jpg',
    slug: 'pate-frango-cenoura',
    receitasRelacionadas: ['2', '10', '14', '18'],
    categoriasRelacionadas: ['Acompanhamentos', 'Pratos Principais'],
  },
  {
    id: '28',
    titulo: 'Pipoca Doce de Leite Condensado',
    descricao: 'Pipoca caramelizada com leite condensado que vira vício em noites de filme em casa',
    categoria: 'Lanches',
    tempoPreparo: 5,
    tempoTotal: 15,
    porcoes: 4,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Milho de pipoca', quantidade: '1/2 xícara' },
      { item: 'Óleo', quantidade: '2 colheres de sopa' },
      { item: 'Manteiga', quantidade: '2 colheres de sopa' },
      { item: 'Leite condensado', quantidade: '1/2 lata' },
      { item: 'Açúcar mascavo', quantidade: '2 colheres de sopa' },
      { item: 'Sal', quantidade: '1 pitada' },
    ],
    modoPreparo: [
      'Em uma panela grande com tampa, aqueça o óleo e o milho de pipoca em fogo alto.',
      'Quando começar a estourar, abaixe o fogo e vá sacudindo a panela de vez em quando.',
      'Espere até que os estouros diminuam e reserve a pipoca em uma tigela.',
      'Na mesma panela, derreta a manteiga e adicione o açúcar mascavo.',
      'Mexa até formar um caramelo claro.',
      'Adicione o leite condensado e uma pitada de sal, misturando bem.',
      'Despeje o caramelo quente sobre a pipoca e misture rápido com duas colheres.',
      'Espalhe em uma assadeira para esfriar e não grudar.',
    ],
    dicas: [
      'Use panela grande para a pipoca não transbordar',
      'Misture o caramelo logo enquanto está quente',
      'Pode adicionar amendoim torrado para dar crocância',
    ],
    imagem: '/images/pipoca-doce.jpg',
    slug: 'pipoca-doce-leite-condensado',
    receitasRelacionadas: ['4', '15', '17', '29'],
    categoriasRelacionadas: ['Lanches', 'Doces'],
  },
  {
    id: '29',
    titulo: 'Pipoca de Chocolate Crocante',
    descricao: 'Pipoca coberta com chocolate meio amargo, crocante por fora e macia por dentro',
    categoria: 'Lanches',
    tempoPreparo: 5,
    tempoTotal: 25,
    porcoes: 4,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Milho de pipoca', quantidade: '1/2 xícara' },
      { item: 'Óleo', quantidade: '2 colheres de sopa' },
      { item: 'Chocolate meio amargo', quantidade: '200g' },
      { item: 'Manteiga', quantidade: '1 colher de sopa' },
      { item: 'Sal', quantidade: '1 pitada' },
      { item: 'Granulado', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Prepare a pipoca na panela com o óleo, até estourar bem.',
      'Separe a pipoca em uma assadeira e retire os milhos que não estouraram.',
      'Derreta o chocolate com a manteiga em banho-maria ou micro-ondas de 30 em 30 segundos.',
      'Despeje o chocolate sobre a pipoca, misturando bem.',
      'Espalhe em uma assadeira forrada com papel manteiga.',
      'Polvilhe o granulado antes do chocolate endurecer.',
      'Leve à geladeira por 10 minutos para ficar crocante.',
      'Sirva em seguida.',
    ],
    dicas: [
      'Use pipoca sem manteiga para o chocolate grudar melhor',
      'Chocolate muito quente pode murchar a pipoca',
      'Armazene em pote fechado para manter a crocância',
    ],
    imagem: '/images/pipoca-chocolate.jpg',
    slug: 'pipoca-chocolate-crocante',
    receitasRelacionadas: ['28', '4', '7', '17'],
    categoriasRelacionadas: ['Lanches', 'Doces'],
  },
  {
    id: '30',
    titulo: 'Caldinho de Feijão Preto da Lurdinha',
    descricao: 'Caldinho de feijão preto cremoso, com gostinho de boteco e cheiro de casa de mãe',
    categoria: 'Sopas',
    tempoPreparo: 15,
    tempoTotal: 40,
    porcoes: 4,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Feijão preto cozido', quantidade: '3 xícaras' },
      { item: 'Caldo de feijão', quantidade: '2 xícaras' },
      { item: 'Bacon em cubos', quantidade: '100g' },
      { item: 'Linguiça calabresa', quantidade: '1 unidade' },
      { item: 'Cebola', quantidade: '1 unidade' },
      { item: 'Alho', quantidade: '3 dentes' },
      { item: 'Coentro', quantidade: 'a gosto' },
      { item: 'Azeite', quantidade: '2 colheres de sopa' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Refogue a cebola e o alho no azeite.',
      'Adicione o bacon e a linguiça em rodelas, frite até dourar.',
      'Acrescente o feijão escorrido e uma parte do caldo.',
      'Bata no liquidificador até metade da mistura e volte para a panela.',
      'Adicione o restante do caldo até ficar na consistência desejada.',
      'Cozinhe por 15 minutos em fogo médio.',
      'Tempere com sal e pimenta.',
      'Sirva bem quente com coentro por cima.',
    ],
    dicas: [
      'Use feijão bem cozido para um caldinho encorpado',
      'Bater metade dá cremosidade sem perder o caldo grosso',
      'Fica perfeito com torradas de pão francês',
    ],
    imagem: '/images/caldinho-feijao.jpg',
    slug: 'caldinho-feijao-preto',
    receitasRelacionadas: ['26', '31', '32', '6'],
    categoriasRelacionadas: ['Sopas', 'Pratos Principais'],
  },
  {
    id: '31',
    titulo: 'Caldinho de Camarão com Leite de Coco',
    descricao: 'Caldinho de camarão cremoso e levemente picante, típico das praias do Nordeste',
    categoria: 'Sopas',
    tempoPreparo: 20,
    tempoTotal: 35,
    porcoes: 4,
    dificuldade: 'médio',
    ingredientes: [
      { item: 'Camarão médio limpo', quantidade: '400g' },
      { item: 'Leite de coco', quantidade: '1 lata' },
      { item: 'Caldo de camarão ou peixe', quantidade: '2 xícaras' },
      { item: 'Cebola', quantidade: '1 unidade' },
      { item: 'Alho', quantidade: '2 dentes' },
      { item: 'Tomate', quantidade: '2 unidades' },
      { item: 'Coentro', quantidade: 'a gosto' },
      { item: 'Azeite', quantidade: '2 colheres de sopa' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
      { item: 'Pimenta dedo-de-moça', quantidade: '1 unidade' },
    ],
    modoPreparo: [
      'Refogue a cebola, o alho e o tomate picado no azeite.',
      'Adicione os camarões e cozinhe por 3 minutos.',
      'Acrescente o caldo, o leite de coco e a pimenta.',
      'Cozinhe por 10 minutos em fogo baixo sem ferver.',
      'Tempere com sal e pimenta.',
      'Finalize com coentro e sirva com torradas.',
    ],
    dicas: [
      'Cuidado para não cozinhar o camarão demais, pode ficar borrachudo',
      'Use camarão bem fresco ou congelado de qualidade',
      'Caldo caseiro de peixe deixa o sabor ainda melhor',
    ],
    imagem: '/images/caldinho-camarao.jpg',
    slug: 'caldinho-camarao-coco',
    receitasRelacionadas: ['30', '11', '32', '6'],
    categoriasRelacionadas: ['Sopas', 'Frutos do Mar'],
  },
  {
    id: '32',
    titulo: 'Caldo Verde da Lurdinha',
    descricao: 'Caldo verde cremoso de batata com couve e linguiça, confortante e cheio de sabor',
    categoria: 'Sopas',
    tempoPreparo: 20,
    tempoTotal: 50,
    porcoes: 6,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Batatas médias', quantidade: '6 unidades' },
      { item: 'Couve manteiga fatiada fina', quantidade: '2 xícaras' },
      { item: 'Linguiça calabresa', quantidade: '1 unidade' },
      { item: 'Alho', quantidade: '3 dentes' },
      { item: 'Cebola', quantidade: '1 unidade' },
      { item: 'Azeite', quantidade: '2 colheres de sopa' },
      { item: 'Caldo de legumes', quantidade: '1 litro' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Refogue a cebola e o alho no azeite.',
      'Adicione as batatas em cubos e o caldo de legumes.',
      'Cozinhe até as batatas estarem bem moles.',
      'Bata a sopa no liquidificador até ficar cremosa.',
      'Volte para a panela, adicione a couve e a linguiça em rodelas.',
      'Cozinhe por mais 5 minutos.',
      'Tempere com sal e pimenta e sirva quente.',
    ],
    dicas: [
      'Fatie a couve bem fininha para não ficar dura',
      'Cozinhe a couve pouco para manter a cor verde',
      'Se preferir, troque a calabresa por paio',
    ],
    imagem: '/images/caldo-verde.jpg',
    slug: 'caldo-verde-lurdinha',
    receitasRelacionadas: ['30', '31', '33', '6'],
    categoriasRelacionadas: ['Sopas', 'Pratos Principais'],
  },
  {
    id: '33',
    titulo: 'Caldo de Quenga da Lurdinha',
    descricao: 'Caldo grosso de mandioca com costela e linguiça, comida de raiz para esquentar o corpo',
    categoria: 'Sopas',
    tempoPreparo: 25,
    tempoTotal: 90,
    porcoes: 6,
    dificuldade: 'médio',
    ingredientes: [
      { item: 'Mandioca descascada', quantidade: '1kg' },
      { item: 'Costela de boi', quantidade: '500g' },
      { item: 'Linguiça paio', quantidade: '2 unidades' },
      { item: 'Cebola', quantidade: '1 unidade' },
      { item: 'Alho', quantidade: '3 dentes' },
      { item: 'Coentro', quantidade: 'a gosto' },
      { item: 'Azeite', quantidade: '2 colheres de sopa' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Cozinhe a costela e a linguiça em água até começarem a ficar macias.',
      'Adicione a mandioca em pedaços e cozinhe até desmanchar.',
      'Em outra panela, refogue a cebola e o alho no azeite.',
      'Acrescente o refogado ao caldo com a mandioca.',
      'Bata metade do caldo no liquidificador para ficar cremoso.',
      'Volte para a panela, tempere com sal e pimenta.',
      'Finalize com coentro e sirva bem quente.',
    ],
    dicas: [
      'Quanto mais a mandioca desmanchar, mais grosso fica o caldo',
      'Costela de boi demora, mas dá o sabor especial',
      'Sobra fica ainda melhor no dia seguinte',
    ],
    imagem: '/images/caldo-quenga.jpg',
    slug: 'caldo-quenga-lurdinha',
    receitasRelacionadas: ['30', '32', '26', '6'],
    categoriasRelacionadas: ['Sopas', 'Pratos Principais'],
  },
  {
    id: '34',
    titulo: 'Almôndegas de Carne Moída na Panela',
    descricao: 'Almôndegas macias e suculentas com molho de tomate caseiro, uma salvação para o almoço de domingo',
    categoria: 'Pratos Principais',
    tempoPreparo: 20,
    tempoTotal: 50,
    porcoes: 5,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Carne moída de acém', quantidade: '500g' },
      { item: 'Ovo', quantidade: '1 unidade' },
      { item: 'Farinha de rosca', quantidade: '1/2 xícara' },
      { item: 'Alho picado', quantidade: '2 dentes' },
      { item: 'Cebola picada', quantidade: '1/2 unidade' },
      { item: 'Salsinha', quantidade: '2 colheres de sopa' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
      { item: 'Óleo para fritar', quantidade: 'a gosto' },
      { item: 'Molho de tomate caseiro', quantidade: '2 xícaras' },
    ],
    modoPreparo: [
      'Misture a carne, o ovo, a farinha de rosca, o alho, a cebola, a salsinha, o sal e a pimenta.',
      'Modele bolinhas do tamanho de uma noz.',
      'Frite levemente no óleo quente para dourar as bordas.',
      'Retire e reserve em papel toalha.',
      'Na mesma panela, aqueça o molho de tomate com um pouco de água.',
      'Coloque as almôndegas no molho e cozinhe por 15 minutos.',
      'Sirva com arroz e purê de batata.',
    ],
    dicas: [
      'Molhe as mãos para modelar sem grudar',
      'Não amasse muito a carne para as almôndegas ficarem macias',
      'Pode congelar cruas e fritar na hora',
    ],
    imagem: '/images/almondegas.jpg',
    slug: 'almondegas-carne-moida',
    receitasRelacionadas: ['2', '16', '26', '25'],
    categoriasRelacionadas: ['Pratos Principais', 'Carnes'],
  },
];

// Função para obter todas as receitas
export function getAllRecipes(): Recipe[] {
  return recipes;
}

// Função para obter receita por slug
export function getRecipeBySlug(slug: string): Recipe | undefined {
  return recipes.find((recipe) => recipe.slug === slug);
}

// Função para obter receitas por categoria
export function getRecipesByCategory(category: string): Recipe[] {
  return recipes.filter((recipe) => recipe.categoria === category);
}

// Função para obter todas as categorias únicas
export function getAllCategories(): string[] {
  const categories = new Set(recipes.map((recipe) => recipe.categoria));
  return Array.from(categories).sort();
}

// Função para buscar receitas por termo
export function searchRecipes(term: string): Recipe[] {
  const lowerTerm = term.toLowerCase();
  return recipes.filter(
    (recipe) =>
      recipe.titulo.toLowerCase().includes(lowerTerm) ||
      recipe.descricao.toLowerCase().includes(lowerTerm) ||
      recipe.ingredientes.some((ing) =>
        ing.item.toLowerCase().includes(lowerTerm)
      )
  );
}
