// Banco de dados de receitas - Conteúdo original e exclusivo
// Cada receita foi reescrita para ser única e evitar plágio

export interface Recipe {
  id: string;
  titulo: string;
  descricao: string;
  categoria: string;
  tempoPreparo: number; // em minutos
  tempoTotal: number; // em minutos
  porcoes: number;
  dificuldade: 'fácil' | 'médio' | 'difícil';
  ingredientes: {
    item: string;
    quantidade: string;
  }[];
  modoPreparo: string[];
  dicas: string[];
  imagem: string;
  slug: string;
}

export const recipes: Recipe[] = [
  {
    id: '1',
    titulo: 'Bolo de Chocolate Intenso',
    descricao: 'Um bolo moist e delicioso com cobertura de ganache cremoso que derrete na boca',
    categoria: 'Bolos',
    tempoPreparo: 20,
    tempoTotal: 50,
    porcoes: 8,
    dificuldade: 'médio',
    ingredientes: [
      { item: 'Chocolate em pó de qualidade', quantidade: '3/4 xícara' },
      { item: 'Farinha de trigo', quantidade: '1 1/2 xícara' },
      { item: 'Açúcar cristal', quantidade: '1 xícara' },
      { item: 'Ovos grandes', quantidade: '3 unidades' },
      { item: 'Óleo vegetal', quantidade: '1/2 xícara' },
      { item: 'Leite integral', quantidade: '3/4 xícara' },
      { item: 'Fermento químico', quantidade: '2 colheres de chá' },
      { item: 'Sal refinado', quantidade: '1/4 colher de chá' },
      { item: 'Extrato de baunilha', quantidade: '1 colher de chá' },
    ],
    modoPreparo: [
      'Pré-aqueça o forno a 180°C. Prepare uma forma redonda de 20cm untando com manteiga e polvilhando farinha.',
      'Em uma tigela, misture o chocolate em pó com a farinha de trigo, açúcar e sal.',
      'Em outro recipiente, bata os ovos com o óleo até ficar homogêneo.',
      'Combine a mistura úmida com a seca, mexendo delicadamente até incorporar bem.',
      'Adicione o leite e o extrato de baunilha, mexendo até obter uma massa lisa.',
      'Despeje na forma preparada e leve ao forno por 30-35 minutos até um palito sair com alguns fios de massa.',
      'Deixe esfriar por 10 minutos na forma antes de desenformar.',
    ],
    dicas: [
      'Use chocolate em pó de boa qualidade para melhor sabor',
      'Não abra o forno durante os primeiros 25 minutos de cozimento',
      'Prepare a cobertura enquanto o bolo esfria',
    ],
    imagem: '/images/bolo-chocolate.jpg',
    slug: 'bolo-chocolate-intenso',
  },
  {
    id: '2',
    titulo: 'Frango Grelhado com Tempero Especial',
    descricao: 'Peito de frango suculento com marinada aromática que realça o sabor natural da carne',
    categoria: 'Pratos Principais',
    tempoPreparo: 30,
    tempoTotal: 45,
    porcoes: 4,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Peito de frango', quantidade: '4 filés (600g)' },
      { item: 'Suco de limão fresco', quantidade: '1/4 xícara' },
      { item: 'Azeite extra virgem', quantidade: '3 colheres de sopa' },
      { item: 'Alho picado', quantidade: '4 dentes' },
      { item: 'Orégano seco', quantidade: '1 colher de chá' },
      { item: 'Tomilho fresco', quantidade: '1 colher de sopa' },
      { item: 'Sal marinho', quantidade: 'a gosto' },
      { item: 'Pimenta preta moída', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Prepare a marinada misturando suco de limão, azeite, alho, orégano, tomilho, sal e pimenta.',
      'Coloque os filés de frango em um recipiente e despeje a marinada sobre eles.',
      'Deixe descansar na geladeira por no mínimo 20 minutos (pode ser até 2 horas).',
      'Aqueça a grelha ou frigideira em fogo alto até ficar bem quente.',
      'Retire o frango da marinada e coloque na grelha, cozinhando 6-7 minutos de cada lado.',
      'Verifique se a carne está cozida no interior (use um termômetro: 75°C).',
      'Deixe descansar por 5 minutos antes de servir.',
    ],
    dicas: [
      'Não coloque o frango na grelha muito frio, deixe atingir temperatura ambiente',
      'Não vire a carne constantemente, apenas uma vez',
      'Se preferir mais suculento, cubra com papel alumínio após cozinhar',
    ],
    imagem: '/images/frango-grelhado.jpg',
    slug: 'frango-grelhado-tempero-especial',
  },
  {
    id: '3',
    titulo: 'Salada Tropical com Vinagrete Cítrico',
    descricao: 'Combinação refrescante de frutas tropicais com folhas verdes e molho agridoce leve',
    categoria: 'Saladas',
    tempoPreparo: 15,
    tempoTotal: 15,
    porcoes: 4,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Folhas de alface roxa', quantidade: '2 xícaras' },
      { item: 'Rúcula fresca', quantidade: '1 xícara' },
      { item: 'Manga madura', quantidade: '1 unidade' },
      { item: 'Abacaxi fresco', quantidade: '1 xícara' },
      { item: 'Morango', quantidade: '200g' },
      { item: 'Coco ralado fresco', quantidade: '1/4 xícara' },
      { item: 'Suco de laranja', quantidade: '1/4 xícara' },
      { item: 'Suco de limão', quantidade: '2 colheres de sopa' },
      { item: 'Azeite suave', quantidade: '3 colheres de sopa' },
      { item: 'Mel puro', quantidade: '1 colher de sopa' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Lave e seque bem as folhas de alface e rúcula.',
      'Descasque e corte a manga em cubos pequenos.',
      'Corte o abacaxi em pedaços pequenos, removendo o miolo duro.',
      'Limpe os morangos e corte-os em fatias.',
      'Prepare o vinagrete misturando suco de laranja, suco de limão, azeite, mel, sal e pimenta.',
      'Em uma tigela grande, coloque as folhas verdes como base.',
      'Distribua as frutas sobre as folhas de forma harmoniosa.',
      'Polvilhe o coco ralado por cima.',
      'Despeje o vinagrete no momento de servir.',
    ],
    dicas: [
      'Prepare o vinagrete com antecedência para os sabores se integrarem',
      'Use frutas bem maduras para melhor sabor',
      'Não misture a salada muito antes de servir para não murchar as folhas',
    ],
    imagem: '/images/salada-tropical.jpg',
    slug: 'salada-tropical-vinagrete-citrico',
  },
  {
    id: '4',
    titulo: 'Brigadeiro Gourmet de Café',
    descricao: 'Doce cremoso com sabor sofisticado de café que impressiona em qualquer ocasião',
    categoria: 'Doces',
    tempoPreparo: 10,
    tempoTotal: 30,
    porcoes: 20,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Leite condensado', quantidade: '1 lata (395g)' },
      { item: 'Chocolate em pó premium', quantidade: '4 colheres de sopa' },
      { item: 'Café expresso coado', quantidade: '2 colheres de sopa' },
      { item: 'Manteiga sem sal', quantidade: '2 colheres de sopa' },
      { item: 'Chocolate granulado', quantidade: 'para cobrir' },
      { item: 'Forminhas de papel', quantidade: '20 unidades' },
    ],
    modoPreparo: [
      'Despeje o leite condensado em uma panela de fundo grosso.',
      'Adicione o chocolate em pó e o café expresso, misturando bem.',
      'Coloque a manteiga e mexa continuamente em fogo médio.',
      'Cozinhe por 8-10 minutos, mexendo sempre, até desgrudar da panela.',
      'Deixe esfriar completamente em um prato untado com manteiga.',
      'Com as mãos untadas, forme bolinhas e coloque nas forminhas.',
      'Passe o chocolate granulado em cada brigadeiro.',
      'Guarde em recipiente fechado na geladeira.',
    ],
    dicas: [
      'Não pare de mexer durante o cozimento para evitar queimar',
      'Use café expresso de qualidade para melhor sabor',
      'Se ficar muito mole, cozinhe mais alguns minutos',
    ],
    imagem: '/images/brigadeiro-cafe.jpg',
    slug: 'brigadeiro-gourmet-cafe',
  },
  {
    id: '5',
    titulo: 'Pasta à Carbonara Autêntica',
    descricao: 'Prato italiano clássico com molho cremoso feito apenas com ovos, queijo e bacon',
    categoria: 'Massas',
    tempoPreparo: 15,
    tempoTotal: 25,
    porcoes: 4,
    dificuldade: 'médio',
    ingredientes: [
      { item: 'Macarrão tipo penne ou spaghetti', quantidade: '400g' },
      { item: 'Bacon fatiado', quantidade: '200g' },
      { item: 'Gema de ovo', quantidade: '3 unidades' },
      { item: 'Queijo parmesão ralado', quantidade: '1 xícara' },
      { item: 'Sal grosso para a água', quantidade: 'a gosto' },
      { item: 'Pimenta preta moída', quantidade: 'a gosto' },
      { item: 'Salsa fresca picada', quantidade: '2 colheres de sopa' },
    ],
    modoPreparo: [
      'Coloque água em uma panela grande com sal grosso e deixe fervendo.',
      'Corte o bacon em tiras pequenas e frite em uma frigideira até ficar crocante.',
      'Retire o bacon e reserve, deixando um pouco do óleo na frigideira.',
      'Cozinhe a massa na água fervente até ficar al dente (siga o tempo da embalagem).',
      'Enquanto a massa cozinha, bata as gemas com o queijo parmesão em uma tigela.',
      'Escorra a massa, reservando 1 xícara da água de cozimento.',
      'Coloque a massa quente na frigideira com o bacon e o óleo.',
      'Desligue o fogo e adicione a mistura de ovos e queijo, mexendo rapidamente.',
      'Se necessário, adicione um pouco da água de cozimento para deixar cremoso.',
      'Tempere com pimenta preta e sirva imediatamente.',
    ],
    dicas: [
      'Não use ovos inteiros, apenas as gemas para melhor cremosidade',
      'Trabalhe rápido após adicionar os ovos para não cozinhá-los demais',
      'A água de cozimento da massa ajuda a criar o molho cremoso',
    ],
    imagem: '/images/pasta-carbonara.jpg',
    slug: 'pasta-carbonara-autentica',
  },
  {
    id: '6',
    titulo: 'Sopa de Abóbora com Gengibre',
    descricao: 'Sopa cremosa e reconfortante com toque picante e aromático de gengibre fresco',
    categoria: 'Sopas',
    tempoPreparo: 20,
    tempoTotal: 40,
    porcoes: 6,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Abóbora madura', quantidade: '1kg' },
      { item: 'Cebola média', quantidade: '1 unidade' },
      { item: 'Gengibre fresco', quantidade: '3 colheres de sopa ralado' },
      { item: 'Alho', quantidade: '2 dentes' },
      { item: 'Caldo de legumes', quantidade: '1 litro' },
      { item: 'Leite de coco', quantidade: '1 xícara' },
      { item: 'Azeite', quantidade: '2 colheres de sopa' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
      { item: 'Cebolinha fresca', quantidade: 'para servir' },
    ],
    modoPreparo: [
      'Descasque a abóbora, retire as sementes e corte em cubos médios.',
      'Aquece o azeite em uma panela grande e refogue a cebola e o alho picados.',
      'Adicione o gengibre ralado e cozinhe por 1 minuto até liberar o aroma.',
      'Coloque os cubos de abóbora e mexa bem para cobrir com o azeite.',
      'Despeje o caldo de legumes e deixe fervendo até a abóbora ficar macia (15-20 minutos).',
      'Retire do fogo e deixe esfriar um pouco.',
      'Bata a sopa no liquidificador ou processador até ficar completamente lisa.',
      'Retorne à panela, adicione o leite de coco e tempere com sal e pimenta.',
      'Aqueça novamente sem deixar fervir.',
      'Sirva quente com cebolinha fresca por cima.',
    ],
    dicas: [
      'Use abóbora bem madura para melhor doçura natural',
      'Se preferir mais espessa, use menos caldo',
      'Pode congelar a sopa por até 3 meses',
    ],
    imagem: '/images/sopa-abobora-gengibre.jpg',
    slug: 'sopa-abobora-gengibre',
  },
  {
    id: '7',
    titulo: 'Cookies de Aveia e Chocolate',
    descricao: 'Biscoitos crocantes por fora e macios por dentro com pedaços generosos de chocolate',
    categoria: 'Biscoitos',
    tempoPreparo: 15,
    tempoTotal: 35,
    porcoes: 24,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Manteiga mole', quantidade: '1/2 xícara' },
      { item: 'Açúcar mascavo', quantidade: '3/4 xícara' },
      { item: 'Açúcar branco', quantidade: '1/4 xícara' },
      { item: 'Ovo', quantidade: '1 unidade' },
      { item: 'Extrato de baunilha', quantidade: '1 colher de chá' },
      { item: 'Farinha de trigo', quantidade: '1 xícara' },
      { item: 'Aveia em flocos', quantidade: '1 1/2 xícara' },
      { item: 'Chocolate em gotas', quantidade: '1 xícara' },
      { item: 'Fermento químico', quantidade: '1/2 colher de chá' },
      { item: 'Sal', quantidade: '1/4 colher de chá' },
    ],
    modoPreparo: [
      'Pré-aqueça o forno a 190°C.',
      'Bata a manteiga com os dois açúcares até ficar cremoso.',
      'Adicione o ovo e o extrato de baunilha, batendo bem.',
      'Em outra tigela, misture a farinha, aveia, fermento e sal.',
      'Combine a mistura seca com a úmida até incorporar bem.',
      'Adicione o chocolate em gotas e misture delicadamente.',
      'Coloque colheradas da massa em uma assadeira forrada com papel manteiga.',
      'Deixe espaço entre os cookies pois vão expandir.',
      'Asse por 10-12 minutos até ficarem dourados nas bordas.',
      'Deixe esfriar na assadeira por 5 minutos antes de transferir para uma grade.',
    ],
    dicas: [
      'Não asse demais para manter o interior macio',
      'Use chocolate de qualidade para melhor sabor',
      'Guarde em pote fechado para manter a maciez',
    ],
    imagem: '/images/cookies-aveia-chocolate.jpg',
    slug: 'cookies-aveia-chocolate',
  },
  {
    id: '8',
    titulo: 'Risoto de Cogumelos Selvagens',
    descricao: 'Prato italiano cremoso e elegante com cogumelos frescos e toque de vinho branco',
    categoria: 'Pratos Principais',
    tempoPreparo: 25,
    tempoTotal: 40,
    porcoes: 4,
    dificuldade: 'médio',
    ingredientes: [
      { item: 'Arroz arbóreo', quantidade: '1 1/2 xícara' },
      { item: 'Cogumelos variados', quantidade: '400g' },
      { item: 'Cebola pequena', quantidade: '1 unidade' },
      { item: 'Alho', quantidade: '2 dentes' },
      { item: 'Vinho branco seco', quantidade: '1/2 xícara' },
      { item: 'Caldo de legumes quente', quantidade: '1 litro' },
      { item: 'Queijo parmesão ralado', quantidade: '1/2 xícara' },
      { item: 'Manteiga', quantidade: '2 colheres de sopa' },
      { item: 'Azeite', quantidade: '2 colheres de sopa' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
      { item: 'Salsa fresca', quantidade: '1 colher de sopa' },
    ],
    modoPreparo: [
      'Limpe os cogumelos com um pano úmido e corte em fatias médias.',
      'Aqueça o azeite em uma frigideira e refogue os cogumelos até dourar. Reserve.',
      'Em uma panela grande, aquece a manteiga e refoga a cebola e alho picados.',
      'Adiciona o arroz e mexe por 2 minutos até ficar translúcido nas bordas.',
      'Despeja o vinho branco e mexe até ser absorvido.',
      'Comece a adicionar o caldo quente em pequenas porções, mexendo constantemente.',
      'Adicione novo caldo apenas quando o anterior for absorvido (cerca de 18-20 minutos).',
      'Quando o arroz estiver al dente, adicione os cogumelos refogados.',
      'Retire do fogo e adicione a manteiga e o queijo parmesão, mexendo bem.',
      'Tempere com sal e pimenta, e sirva imediatamente com salsa fresca.',
    ],
    dicas: [
      'Mantenha o caldo sempre quente para melhor absorção',
      'Mexa constantemente para liberar o amido do arroz e criar cremosidade',
      'Use cogumelos frescos de qualidade para melhor sabor',
    ],
    imagem: '/images/risoto-cogumelos.jpg',
    slug: 'risoto-cogumelos-selvagens',
  },
  {
    id: '9',
    titulo: 'Smoothie Bowl de Açaí',
    descricao: 'Tigela colorida e nutritiva com açaí cremoso e cobertura de frutas e granola',
    categoria: 'Café da Manhã',
    tempoPreparo: 10,
    tempoTotal: 10,
    porcoes: 2,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Polpa de açaí congelada', quantidade: '200g' },
      { item: 'Leite de amêndoa', quantidade: '1/2 xícara' },
      { item: 'Banana congelada', quantidade: '1 unidade' },
      { item: 'Mel puro', quantidade: '1 colher de sopa' },
      { item: 'Granola caseira', quantidade: '1/2 xícara' },
      { item: 'Morango fresco', quantidade: '100g' },
      { item: 'Blueberry', quantidade: '100g' },
      { item: 'Coco ralado', quantidade: '2 colheres de sopa' },
      { item: 'Sementes de chia', quantidade: '1 colher de sopa' },
    ],
    modoPreparo: [
      'Coloque a polpa de açaí, leite de amêndoa, banana congelada e mel no liquidificador.',
      'Bata até obter uma consistência de sorvete (cremosa mas não líquida).',
      'Divida a mistura em duas tigelas.',
      'Distribua a granola sobre o açaí.',
      'Coloque os morangos cortados em fatias.',
      'Adicione os blueberries de forma decorativa.',
      'Polvilhe o coco ralado e as sementes de chia.',
      'Sirva imediatamente com uma colher.',
    ],
    dicas: [
      'Use frutas congeladas para melhor consistência',
      'Prepare a cobertura enquanto bate o açaí',
      'Customize com suas frutas e sementes favoritas',
    ],
    imagem: '/images/smoothie-bowl-acai.jpg',
    slug: 'smoothie-bowl-acai',
  },
  {
    id: '10',
    titulo: 'Pão Caseiro de Fermentação Natural',
    descricao: 'Pão artesanal com crosta crocante e miolo macio feito com fermento natural',
    categoria: 'Pães',
    tempoPreparo: 30,
    tempoTotal: 480,
    porcoes: 1,
    dificuldade: 'difícil',
    ingredientes: [
      { item: 'Farinha de trigo integral', quantidade: '500g' },
      { item: 'Água filtrada', quantidade: '350ml' },
      { item: 'Fermento natural ativo', quantidade: '100g' },
      { item: 'Sal marinho', quantidade: '10g' },
      { item: 'Azeite', quantidade: '1 colher de sopa' },
    ],
    modoPreparo: [
      'Misture a farinha, água e fermento natural em uma tigela grande.',
      'Deixe descansar por 30 minutos (autólise).',
      'Adicione o sal e o azeite, mexendo bem até incorporar.',
      'Deixe fermentar em temperatura ambiente por 4-6 horas, dobrando a massa a cada 30 minutos.',
      'Coloque a massa em uma superfície enfarinhada e dê forma redonda.',
      'Deixe descansar por 2 horas em um cesto de fermentação ou tigela forrada.',
      'Pré-aqueça o forno a 250°C com uma assadeira dentro.',
      'Vire a massa para a assadeira quente com cuidado.',
      'Faça um corte na superfície com uma faca afiada.',
      'Asse por 35-40 minutos até ficar dourado e soar oco quando batido.',
      'Deixe esfriar completamente antes de cortar.',
    ],
    dicas: [
      'Mantenha o fermento natural alimentado regularmente',
      'A temperatura ambiente afeta o tempo de fermentação',
      'Use água filtrada para melhor resultado',
    ],
    imagem: '/images/pao-fermentacao-natural.jpg',
    slug: 'pao-caseiro-fermentacao-natural',
  },
  {
    id: '11',
    titulo: 'Ceviche Peruano Tradicional',
    descricao: 'Prato refrescante com peixe fresco marinado em suco cítrico com toque picante',
    categoria: 'Frutos do Mar',
    tempoPreparo: 20,
    tempoTotal: 30,
    porcoes: 4,
    dificuldade: 'médio',
    ingredientes: [
      { item: 'Peixe branco fresco', quantidade: '600g' },
      { item: 'Suco de limão fresco', quantidade: '1 xícara' },
      { item: 'Cebola roxa', quantidade: '1 unidade' },
      { item: 'Pimenta vermelha', quantidade: '1 unidade' },
      { item: 'Coentro fresco', quantidade: '1/4 xícara' },
      { item: 'Sal marinho', quantidade: 'a gosto' },
      { item: 'Pimenta preta', quantidade: 'a gosto' },
      { item: 'Batata doce', quantidade: '2 unidades' },
      { item: 'Milho cozido', quantidade: '1 xícara' },
    ],
    modoPreparo: [
      'Corte o peixe em cubos pequenos e uniforme.',
      'Coloque o peixe em uma tigela e despeje o suco de limão cobrindo completamente.',
      'Deixe marinar na geladeira por 15-20 minutos até o peixe ficar opaco.',
      'Enquanto isso, corte a cebola em meia-lua fina.',
      'Retire as sementes da pimenta e pique em tiras finas.',
      'Pique o coentro fresco.',
      'Cozinhe a batata doce até ficar macia e corte em rodelas.',
      'Retire o peixe da marinada e coloque em uma tigela.',
      'Adicione a cebola, pimenta, coentro, sal e pimenta preta.',
      'Misture delicadamente e sirva em taças com batata doce e milho ao lado.',
    ],
    dicas: [
      'Use peixe absolutamente fresco, de preferência do dia',
      'O suco de limão "cozinha" o peixe através da marinada',
      'Não deixe marinar por mais de 20 minutos para não ficar muito mole',
    ],
    imagem: '/images/ceviche-peruano.jpg',
    slug: 'ceviche-peruano-tradicional',
  },
  {
    id: '12',
    titulo: 'Torta de Maçã com Canela',
    descricao: 'Sobremesa clássica com maçãs caramelizadas e massa folhada crocante',
    categoria: 'Bolos',
    tempoPreparo: 25,
    tempoTotal: 50,
    porcoes: 8,
    dificuldade: 'médio',
    ingredientes: [
      { item: 'Massa folhada pronta', quantidade: '500g' },
      { item: 'Maçã verde', quantidade: '4 unidades' },
      { item: 'Açúcar cristal', quantidade: '1/2 xícara' },
      { item: 'Canela em pó', quantidade: '2 colheres de chá' },
      { item: 'Suco de limão', quantidade: '2 colheres de sopa' },
      { item: 'Manteiga', quantidade: '3 colheres de sopa' },
      { item: 'Farinha de trigo', quantidade: '1 colher de sopa' },
      { item: 'Gema de ovo', quantidade: '1 unidade' },
      { item: 'Água', quantidade: '1 colher de sopa' },
    ],
    modoPreparo: [
      'Pré-aqueça o forno a 200°C.',
      'Descasque as maçãs, retire o miolo e corte em fatias finas.',
      'Coloque as fatias em uma tigela com suco de limão para não escurecer.',
      'Em uma frigideira, derreta a manteiga e adicione o açúcar e a canela.',
      'Coloque as maçãs e cozinhe por 5-7 minutos até caramelizar, mexendo ocasionalmente.',
      'Deixe esfriar um pouco.',
      'Estenda a massa folhada em uma forma de torta.',
      'Polvilhe a farinha sobre a massa.',
      'Distribua as maçãs caramelizadas sobre a massa.',
      'Dobre as bordas da massa sobre as maçãs.',
      'Misture a gema com a água e pincele sobre a massa.',
      'Asse por 25-30 minutos até a massa ficar dourada.',
      'Deixe esfriar antes de servir.',
    ],
    dicas: [
      'Use maçãs verdes para melhor equilíbrio de sabor',
      'A caramelização das maçãs é essencial para o sabor',
      'Sirva morna com sorvete de baunilha',
    ],
    imagem: '/images/torta-maca-canela.jpg',
    slug: 'torta-maca-canela',
  },
  {
    id: '13',
    titulo: 'Tacos de Carnitas Mexicanos',
    descricao: 'Carne suculenta e desfiada com temperos mexicanos tradicionais em tortilhas quentes',
    categoria: 'Pratos Principais',
    tempoPreparo: 30,
    tempoTotal: 180,
    porcoes: 6,
    dificuldade: 'médio',
    ingredientes: [
      { item: 'Paleta de porco', quantidade: '1kg' },
      { item: 'Laranja', quantidade: '2 unidades' },
      { item: 'Limão', quantidade: '2 unidades' },
      { item: 'Alho', quantidade: '6 dentes' },
      { item: 'Cominho em grão', quantidade: '1 colher de chá' },
      { item: 'Orégano seco', quantidade: '1 colher de chá' },
      { item: 'Louro', quantidade: '2 folhas' },
      { item: 'Sal grosso', quantidade: 'a gosto' },
      { item: 'Pimenta preta', quantidade: 'a gosto' },
      { item: 'Tortilhas de milho', quantidade: '12 unidades' },
      { item: 'Cebola roxa', quantidade: '1 unidade' },
      { item: 'Coentro fresco', quantidade: 'para servir' },
    ],
    modoPreparo: [
      'Corte a paleta de porco em cubos grandes.',
      'Esprema o suco das laranjas e limões.',
      'Em uma panela grande, coloque a carne, sucos cítricos, alho inteiro, cominho, orégano, louro, sal e pimenta.',
      'Deixe fervendo e depois reduza o fogo para baixo.',
      'Cozinhe por 2-3 horas até a carne ficar muito macia e desfiável.',
      'Retire a carne e deixe esfriar um pouco.',
      'Desfie a carne com dois garfos.',
      'Coloque a carne desfiada em uma frigideira com um pouco do caldo de cozimento.',
      'Cozinhe em fogo alto até ficar crocante nas bordas (5-10 minutos).',
      'Aqueça as tortilhas em uma frigideira ou chama direta.',
      'Monte os tacos com a carne, cebola roxa picada e coentro fresco.',
    ],
    dicas: [
      'A carne deve desfilar facilmente quando cozida o suficiente',
      'Guarde o caldo para molhar a carne depois',
      'Sirva com limão, salsa e guacamole',
    ],
    imagem: '/images/tacos-carnitas.jpg',
    slug: 'tacos-carnitas-mexicanos',
  },
  {
    id: '14',
    titulo: 'Quiche de Brócolis e Queijo',
    descricao: 'Torta salgada cremosa com brócolis fresco e queijo derretido em massa crocante',
    categoria: 'Pratos Principais',
    tempoPreparo: 20,
    tempoTotal: 50,
    porcoes: 6,
    dificuldade: 'médio',
    ingredientes: [
      { item: 'Massa de torta pronta', quantidade: '1 unidade' },
      { item: 'Brócolis fresco', quantidade: '300g' },
      { item: 'Queijo cheddar ralado', quantidade: '1 xícara' },
      { item: 'Ovos', quantidade: '3 unidades' },
      { item: 'Leite integral', quantidade: '1 xícara' },
      { item: 'Cebola pequena', quantidade: '1 unidade' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
      { item: 'Noz-moscada', quantidade: '1/4 colher de chá' },
      { item: 'Manteiga', quantidade: '1 colher de sopa' },
    ],
    modoPreparo: [
      'Pré-aqueça o forno a 190°C.',
      'Coloque a massa de torta em uma forma de 25cm e fure o fundo com um garfo.',
      'Corte o brócolis em pequenos floretes.',
      'Cozinhe o brócolis em água com sal por 3-4 minutos até ficar al dente. Escorra bem.',
      'Pique a cebola finamente e refogue na manteiga até ficar morna.',
      'Em uma tigela, bata os ovos com o leite, sal, pimenta e noz-moscada.',
      'Distribua o brócolis e a cebola sobre a massa.',
      'Polvilhe o queijo ralado sobre os vegetais.',
      'Despeje a mistura de ovos e leite cuidadosamente.',
      'Asse por 30-35 minutos até ficar dourado e firme no centro.',
      'Deixe esfriar por 10 minutos antes de servir.',
    ],
    dicas: [
      'Cozinhe o brócolis al dente para não ficar mole demais',
      'A quiche pode ser feita com antecedência e reaquecida',
      'Experimente com diferentes queijos para variar',
    ],
    imagem: '/images/quiche-brocolis-queijo.jpg',
    slug: 'quiche-brocolis-queijo',
  },
  {
    id: '15',
    titulo: 'Pudim de Leite Condensado',
    descricao: 'Sobremesa clássica cremosa com calda de caramelo que derrete na boca',
    categoria: 'Doces',
    tempoPreparo: 15,
    tempoTotal: 240,
    porcoes: 8,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Leite condensado', quantidade: '1 lata (395g)' },
      { item: 'Leite integral', quantidade: '1 lata (200ml)' },
      { item: 'Ovos', quantidade: '4 unidades' },
      { item: 'Açúcar para caramelo', quantidade: '1 xícara' },
      { item: 'Água', quantidade: '1/2 xícara' },
    ],
    modoPreparo: [
      'Pré-aqueça o forno a 180°C.',
      'Prepare uma forma redonda de 20cm.',
      'Em uma panela, coloque o açúcar e a água para fazer o caramelo.',
      'Cozinhe em fogo médio até ficar dourado (não mexa, apenas incline a panela).',
      'Despeje o caramelo rapidamente na forma, cobrindo o fundo e as laterais.',
      'No liquidificador, bata o leite condensado, leite integral e ovos até ficar homogêneo.',
      'Despeje a mistura sobre o caramelo.',
      'Coloque a forma em uma assadeira maior com água quente até a metade da altura.',
      'Asse por 50-60 minutos até ficar firme mas ainda um pouco mole no centro.',
      'Deixe esfriar completamente e leve à geladeira por no mínimo 4 horas.',
      'Para desenformar, passe uma faca nas laterais e vire em um prato.',
    ],
    dicas: [
      'O pudim continua cozinhando após sair do forno, não deixe muito firme',
      'A calda de caramelo é o que torna especial, não pule essa etapa',
      'Pode ser feito com 1 dia de antecedência',
    ],
    imagem: '/images/pudim-leite-condensado.jpg',
    slug: 'pudim-leite-condensado',
  },
  {
    id: '16',
    titulo: 'Steak com Molho de Vinho Tinto',
    descricao: 'Carne vermelha suculenta com molho elegante e aromático de vinho tinto',
    categoria: 'Pratos Principais',
    tempoPreparo: 20,
    tempoTotal: 35,
    porcoes: 2,
    dificuldade: 'médio',
    ingredientes: [
      { item: 'Bife ancho', quantidade: '2 unidades (300g cada)' },
      { item: 'Vinho tinto seco', quantidade: '1 xícara' },
      { item: 'Caldo de carne', quantidade: '1 xícara' },
      { item: 'Manteiga', quantidade: '3 colheres de sopa' },
      { item: 'Alho', quantidade: '3 dentes' },
      { item: 'Tomilho fresco', quantidade: '2 ramos' },
      { item: 'Sal grosso', quantidade: 'a gosto' },
      { item: 'Pimenta preta moída', quantidade: 'a gosto' },
      { item: 'Azeite', quantidade: '2 colheres de sopa' },
    ],
    modoPreparo: [
      'Retire os bifes da geladeira 30 minutos antes de cozinhar.',
      'Tempere generosamente com sal grosso e pimenta preta.',
      'Aqueça o azeite em uma frigideira de ferro até ficar bem quente.',
      'Coloque os bifes e cozinhe 4-5 minutos de cada lado para ponto médio.',
      'Retire os bifes e deixe descansar em um prato.',
      'Na mesma frigideira, adicione o alho e tomilho, refogando por 1 minuto.',
      'Despeje o vinho tinto e deixe reduzir pela metade (3-4 minutos).',
      'Adicione o caldo de carne e deixe reduzir novamente até ficar cremoso.',
      'Retire do fogo e adicione a manteiga em pequenos pedaços, mexendo bem.',
      'Coloque os bifes no prato e despeje o molho por cima.',
    ],
    dicas: [
      'Não vire a carne constantemente, apenas uma vez',
      'Use um termômetro: 55°C para raro, 60°C para médio',
      'Deixar descansar é essencial para manter o suco',
    ],
    imagem: '/images/steak-molho-vinho.jpg',
    slug: 'steak-molho-vinho-tinto',
  },
  {
    id: '17',
    titulo: 'Pavê de Chocolate',
    descricao: 'Sobremesa gelada em camadas com biscoito, creme e chocolate derretido',
    categoria: 'Doces',
    tempoPreparo: 30,
    tempoTotal: 300,
    porcoes: 10,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Biscoito de polvilho', quantidade: '400g' },
      { item: 'Leite integral', quantidade: '1 xícara' },
      { item: 'Chocolate em pó', quantidade: '1/2 xícara' },
      { item: 'Açúcar', quantidade: '1/2 xícara' },
      { item: 'Gema de ovo', quantidade: '3 unidades' },
      { item: 'Manteiga mole', quantidade: '1/2 xícara' },
      { item: 'Leite condensado', quantidade: '1 lata (395g)' },
      { item: 'Chocolate em gotas', quantidade: '1 xícara' },
      { item: 'Café coado', quantidade: '1/2 xícara' },
    ],
    modoPreparo: [
      'Prepare uma forma retangular de 25x35cm.',
      'Misture o café coado com um pouco de água.',
      'Mergulhe rapidamente cada biscoito no café e coloque na forma em uma camada.',
      'Em uma panela, coloque a manteiga, açúcar e gemas, cozinhando em banho-maria até ficar cremoso.',
      'Retire do fogo e deixe esfriar um pouco.',
      'Adicione o leite condensado e misture bem.',
      'Espalhe metade do creme sobre a camada de biscoito.',
      'Faça outra camada de biscoito mergulhado em café.',
      'Espalhe o restante do creme.',
      'Faça a última camada de biscoito.',
      'Derreta o chocolate com um pouco de leite e espalhe sobre o pavê.',
      'Leve à geladeira por no mínimo 4 horas antes de servir.',
    ],
    dicas: [
      'Não deixe o biscoito muito tempo no café para não ficar encharcado',
      'O pavê fica melhor no dia seguinte quando os sabores se integram',
      'Pode ser feito com 2 dias de antecedência',
    ],
    imagem: '/images/pave-chocolate.jpg',
    slug: 'pave-chocolate',
  },
  {
    id: '18',
    titulo: 'Frittata de Vegetais',
    descricao: 'Omelete italiana assada com vegetais frescos e queijo derretido',
    categoria: 'Café da Manhã',
    tempoPreparo: 15,
    tempoTotal: 25,
    porcoes: 4,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Ovos', quantidade: '8 unidades' },
      { item: 'Pimentão vermelho', quantidade: '1 unidade' },
      { item: 'Cebola pequena', quantidade: '1 unidade' },
      { item: 'Espinafre fresco', quantidade: '2 xícaras' },
      { item: 'Queijo mozzarela ralado', quantidade: '1 xícara' },
      { item: 'Azeite', quantidade: '2 colheres de sopa' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
      { item: 'Orégano seco', quantidade: '1/2 colher de chá' },
    ],
    modoPreparo: [
      'Pré-aqueça o forno a 190°C.',
      'Corte o pimentão e a cebola em cubos pequenos.',
      'Aqueça o azeite em uma frigideira antiaderente e refogue a cebola e pimentão por 3 minutos.',
      'Adicione o espinafre e cozinhe até murchar (2 minutos).',
      'Em uma tigela, bata os ovos com sal, pimenta e orégano.',
      'Despeje os ovos sobre os vegetais na frigideira.',
      'Cozinhe em fogo médio por 3-4 minutos até as bordas começarem a ficar firmes.',
      'Polvilhe o queijo sobre a mistura.',
      'Coloque a frigideira no forno por 8-10 minutos até ficar dourado.',
      'Deixe esfriar um pouco, corte em fatias e sirva.',
    ],
    dicas: [
      'Use uma frigideira que possa ir ao forno',
      'Customize com seus vegetais favoritos',
      'Ótima para aproveitar vegetais que sobraram',
    ],
    imagem: '/images/frittata-vegetais.jpg',
    slug: 'frittata-vegetais',
  },
  {
    id: '19',
    titulo: 'Molho Pesto Caseiro',
    descricao: 'Molho aromático e fresco com manjericão, alho, pinhão e azeite de qualidade',
    categoria: 'Molhos',
    tempoPreparo: 10,
    tempoTotal: 10,
    porcoes: 8,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Folhas de manjericão fresco', quantidade: '2 xícaras' },
      { item: 'Alho', quantidade: '3 dentes' },
      { item: 'Pinhão', quantidade: '1/2 xícara' },
      { item: 'Queijo parmesão ralado', quantidade: '1/2 xícara' },
      { item: 'Azeite extra virgem', quantidade: '3/4 xícara' },
      { item: 'Suco de limão', quantidade: '1 colher de sopa' },
      { item: 'Sal marinho', quantidade: 'a gosto' },
      { item: 'Pimenta preta', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Coloque o manjericão, alho e pinhão no processador de alimentos.',
      'Pulse até ficar picado mas ainda com textura.',
      'Adicione o queijo parmesão e pulse novamente.',
      'Com o processador ligado, adicione o azeite lentamente até obter a consistência desejada.',
      'Adicione o suco de limão, sal e pimenta.',
      'Pulse uma última vez para incorporar bem.',
      'Transfira para um pote de vidro.',
      'Se quiser armazenar, cubra com uma camada de azeite.',
    ],
    dicas: [
      'Use manjericão fresco de qualidade para melhor sabor',
      'Não cozinhe o pesto, use apenas em pratos frios ou adicione no final',
      'Guarde na geladeira por até 1 semana',
    ],
    imagem: '/images/molho-pesto.jpg',
    slug: 'molho-pesto-caseiro',
  },
  {
    id: '20',
    titulo: 'Soufflé de Queijo',
    descricao: 'Prato elegante e leve com queijo derretido que sobe no forno de forma impressionante',
    categoria: 'Pratos Principais',
    tempoPreparo: 20,
    tempoTotal: 35,
    porcoes: 4,
    dificuldade: 'difícil',
    ingredientes: [
      { item: 'Manteiga', quantidade: '3 colheres de sopa' },
      { item: 'Farinha de trigo', quantidade: '3 colheres de sopa' },
      { item: 'Leite integral', quantidade: '1 xícara' },
      { item: 'Queijo gruyère ralado', quantidade: '1 xícara' },
      { item: 'Gema de ovo', quantidade: '4 unidades' },
      { item: 'Claras de ovo', quantidade: '5 unidades' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
      { item: 'Noz-moscada', quantidade: '1/4 colher de chá' },
      { item: 'Manteiga para untar', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Pré-aqueça o forno a 200°C.',
      'Unte 4 ramequins individuais com manteiga e polvilhe farinha.',
      'Em uma panela, derreta a manteiga em fogo médio.',
      'Adicione a farinha e mexa por 1 minuto para fazer um roux.',
      'Adicione o leite gradualmente, mexendo constantemente até ficar liso.',
      'Cozinhe por 2-3 minutos até engrossar.',
      'Retire do fogo e adicione o queijo, sal, pimenta e noz-moscada.',
      'Deixe esfriar um pouco e adicione as gemas uma a uma, mexendo bem.',
      'Em outra tigela, bata as claras em ponto de neve firme.',
      'Incorpore delicadamente as claras à mistura de queijo em 3 partes.',
      'Distribua nos ramequins preparados.',
      'Asse por 15-20 minutos até ficar dourado e firme nas laterais mas ainda mole no centro.',
      'Sirva imediatamente.',
    ],
    dicas: [
      'Não abra o forno durante o cozimento para não descer',
      'As claras em ponto de neve são essenciais para o soufflé subir',
      'Sirva imediatamente após sair do forno',
    ],
    imagem: '/images/souffle-queijo.jpg',
    slug: 'souffle-queijo',
  },
  {
    id: '21',
    titulo: 'Bolo no Pote da Lurdinha',
    descricao: 'Bolinhos individuais de chocolate com recheio cremoso que fazem sucesso na hora de vender ou presentear',
    categoria: 'Bolos',
    tempoPreparo: 25,
    tempoTotal: 55,
    porcoes: 6,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Farinha de trigo', quantidade: '1 1/2 xícara' },
      { item: 'Açúcar', quantidade: '1 xícara' },
      { item: 'Ovos', quantidade: '2 unidades' },
      { item: 'Leite', quantidade: '1/2 xícara' },
      { item: 'Óleo', quantidade: '1/3 xícara' },
      { item: 'Chocolate em pó', quantidade: '1/2 xícara' },
      { item: 'Fermento em pó', quantidade: '1 colher de sopa' },
      { item: 'Leite condensado', quantidade: '1 lata' },
      { item: 'Creme de leite', quantidade: '1/2 lata' },
      { item: 'Chocolate meio amargo', quantidade: '200g' },
      { item: 'Granulado', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Pré-aqueça o forno a 180°C.',
      'Em uma tigela, misture a farinha, o açúcar, o chocolate em pó e o fermento.',
      'Adicione os ovos, o leite e o óleo, batendo até ficar homogêneo.',
      'Despeje a massa em potinhos de vidro individuais até dois terços da altura.',
      'Asse por 25 a 30 minutos ou até o palito sair limpo.',
      'Deixe os bolinhos esfriar completamente.',
      'Prepare a cobertura: leve o leite condensado, creme de leite e chocolate ao fogo baixo até derreter e engrossar.',
      'Faça um buraco no centro de cada bolo e recheie com parte da cobertura.',
      'Cubra com a cobertura restante e decore com granulado.',
      'Sirva em seguida ou guarde na geladeira por até 3 dias.',
    ],
    dicas: [
      'Use potinhos de vidro ou plástico próprios para alimentos',
      'Cobertura fica melhor quando esfria um pouco antes de usar',
      'Esses bolos são ótimos para vender ou levar em encontros',
    ],
    imagem: '/images/placeholder.svg',
    slug: 'bolo-no-pote-lurdinha',
  },
  {
    id: '22',
    titulo: 'Pudim de Leite da Lurdinha',
    descricao: 'Pudim lisinho, sem furinhos, com calda de caramelo feita na pressão certa para não amargar',
    categoria: 'Doces',
    tempoPreparo: 15,
    tempoTotal: 90,
    porcoes: 8,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Açúcar', quantidade: '1 1/2 xícara' },
      { item: 'Ovos', quantidade: '4 unidades' },
      { item: 'Leite condensado', quantidade: '1 lata' },
      { item: 'Leite integral', quantidade: '2 medidas da lata de leite condensado' },
      { item: 'Baunilha', quantidade: '1 colher de chá' },
    ],
    modoPreparo: [
      'Derreta o açúcar em fogo médio até formar um caramelo dourado.',
      'Despeje o caramelo na forma de pudim, espalhando pelo fundo.',
      'No liquidificador, bata os ovos, o leite condensado, o leite e a baunilha por 3 minutos.',
      'Despeje a mistura na forma caramelizada.',
      'Asse em banho-maria a 180°C por 50 a 60 minutos.',
      'Espete um palito: deve sair levemente úmido.',
      'Deixe esfriar e leve à geladeira por no mínimo 4 horas.',
      'Para desenformar, passe uma faca nas bordas e vire sobre um prato.',
    ],
    dicas: [
      'Não deixe o caramelo escurecer demais para não amargar',
      'Bater a mistura direitinho evita furinhos no pudim',
      'O pudim fica melhor no dia seguinte',
    ],
    imagem: '/images/pudim-leite-condensado.jpg',
    slug: 'pudim-leite-lurdinha',
  },
  {
    id: '23',
    titulo: 'Pavê de Bolacha Mais Cremoso do Mundo',
    descricao: 'Camadas de bolacha molhada em café, creme de chocolate e chantilly que lembram os domingos na casa da minha avó',
    categoria: 'Doces',
    tempoPreparo: 30,
    tempoTotal: 240,
    porcoes: 12,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Bolacha tipo maisena', quantidade: '1 pacote' },
      { item: 'Café coado forte', quantidade: '2 xícaras' },
      { item: 'Leite condensado', quantidade: '1 lata' },
      { item: 'Leite integral', quantidade: '2 xícaras' },
      { item: 'Gemas', quantidade: '4 unidades' },
      { item: 'Amido de milho', quantidade: '3 colheres de sopa' },
      { item: 'Chocolate em pó', quantidade: '4 colheres de sopa' },
      { item: 'Creme de leite', quantidade: '1 lata' },
      { item: 'Chantilly pronto', quantidade: '1 pote' },
      { item: 'Chocolate granulado', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Prepare o creme: leve ao fogo o leite condensado, o leite, as gemas, o amido, o chocolate em pó e o creme de leite.',
      'Mexa sem parar até engrossar e formar um creme liso.',
      'Deixe o creme esfriar, cobrindo com plástico em contato.',
      'Misture o café com um pouco de água morna para molhar a bolacha.',
      'Em um refratário, faça uma camada de bolachas molhadas.',
      'Cubra com uma camada de creme.',
      'Repita as camadas até acabar os ingredientes, finalizando com creme.',
      'Cubra com chantilly e granulado.',
      'Leve à geladeira por pelo menos 4 horas, melhor de um dia para o outro.',
    ],
    dicas: [
      'Molhe a bolacha rapidamente para não derreter',
      'O pavê fica melhor quando os sabores se integram de um dia para o outro',
      'Pode substituir o chantilly por clara em neve se preferir',
    ],
    imagem: '/images/pave-chocolate.jpg',
    slug: 'pave-bolacha-cremoso',
  },
  {
    id: '24',
    titulo: 'Bolo de Milho Cremoso de Liquidificador',
    descricao: 'Bolo de milho fofinho e úmido que sai do liquidificador direto para o forno, perfeito para o café da tarde',
    categoria: 'Bolos',
    tempoPreparo: 10,
    tempoTotal: 50,
    porcoes: 10,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Milho verde', quantidade: '2 xícaras' },
      { item: 'Ovos', quantidade: '3 unidades' },
      { item: 'Açúcar', quantidade: '1 xícara' },
      { item: 'Manteiga derretida', quantidade: '1/2 xícara' },
      { item: 'Leite', quantidade: '1 xícara' },
      { item: 'Fubá', quantidade: '1 xícara' },
      { item: 'Farinha de trigo', quantidade: '1/2 xícara' },
      { item: 'Fermento em pó', quantidade: '1 colher de sopa' },
      { item: 'Erva-doce', quantidade: '1 colher de chá' },
    ],
    modoPreparo: [
      'Pré-aqueça o forno a 180°C e unte uma forma retangular.',
      'No liquidificador, bata o milho, os ovos, o açúcar, a manteiga e o leite.',
      'Adicione o fubá, a farinha, o fermento e a erva-doce e bata rapidamente para misturar.',
      'Despeje a massa na forma.',
      'Asse por 40 a 45 minutos até dourar e o palito sair limpo.',
      'Deixe esfriar um pouco antes de cortar em quadrados.',
    ],
    dicas: [
      'Use milho verde fresco para sabor mais intenso',
      'Pode adicionar coco ralado se gostar',
      'Fica ótimo acompanhado de café com leite',
    ],
    imagem: '/images/placeholder.svg',
    slug: 'bolo-milho-cremoso',
  },
  {
    id: '25',
    titulo: 'Cuscuz Recheado de Carne do Sertão',
    descricao: 'Cuscuz nordestino recheado com carne seca desfiada, uma receita que meu pai fazia nos domingos',
    categoria: 'Pratos Principais',
    tempoPreparo: 30,
    tempoTotal: 60,
    porcoes: 4,
    dificuldade: 'médio',
    ingredientes: [
      { item: 'Flocão de milho', quantidade: '2 xícaras' },
      { item: 'Água morna', quantidade: '2 xícaras' },
      { item: 'Sal', quantidade: '1 colher de chá' },
      { item: 'Carne seca dessalgada e cozida', quantidade: '300g' },
      { item: 'Cebola picada', quantidade: '1 unidade' },
      { item: 'Tomate picado', quantidade: '2 unidades' },
      { item: 'Coentro', quantidade: 'a gosto' },
      { item: 'Azeite', quantidade: '2 colheres de sopa' },
      { item: 'Manteiga', quantidade: '1 colher de sopa' },
    ],
    modoPreparo: [
      'Hidrate o flocão com água morna e sal, deixando descansar 10 minutos.',
      'Refogue a cebola no azeite até dourar.',
      'Adicione o tomate e a carne seca desfiada, cozinhe por 5 minutos.',
      'Finalize com coentro e reserve.',
      'Forre o fundo de uma cuscuzeira com uma parte do flocão hidratado.',
      'Coloque o recheio de carne seca no centro.',
      'Cubra com o restante do flocão.',
      'Leve ao fogo para cozinhar no vapor por 20 a 25 minutos.',
      'Sirva quente com manteiga por cima.',
    ],
    dicas: [
      'A carne seca precisa ser bem dessalgada antes de usar',
      'Não amasse o cuscuz para ele ficar soltinho',
      'Bom a qualquer hora do dia, do café da manhã ao jantar',
    ],
    imagem: '/images/placeholder.svg',
    slug: 'cuscuz-recheado-carne',
  },
  {
    id: '26',
    titulo: 'Feijoada da Lurdinha Sem Complicação',
    descricao: 'Feijoada caseira e cheia de sabor, feita no dia a dia sem precisar de ocasião especial',
    categoria: 'Pratos Principais',
    tempoPreparo: 30,
    tempoTotal: 120,
    porcoes: 6,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Feijão preto', quantidade: '500g' },
      { item: 'Linguiça calabresa', quantidade: '300g' },
      { item: 'Paio', quantidade: '200g' },
      { item: 'Costela de porco', quantidade: '400g' },
      { item: 'Bacon em cubos', quantidade: '100g' },
      { item: 'Alho', quantidade: '4 dentes' },
      { item: 'Cebola', quantidade: '1 unidade' },
      { item: 'Folhas de louro', quantidade: '2 unidades' },
      { item: 'Laranja', quantidade: '1 unidade' },
      { item: 'Azeite', quantidade: '2 colheres de sopa' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Deixe o feijão de molho por 8 horas e escorra.',
      'Cozinhe o feijão com água e o lombo de ouro ou costela até começar a ficar macio.',
      'Em outra panela, refogue o alho, a cebola, o bacon e as linguiças.',
      'Adicione o feijão cozido com um pouco do caldo para a panela de temperos.',
      'Cozinhe por mais 40 minutos em fogo baixo.',
      'Adicione as folhas de louro e a laranja cortada em rodelas.',
      'Ajuste o sal e a pimenta.',
      'Sirva com arroz branco, couve refogada e farofa.',
    ],
    dicas: [
      'O laranja ajuda a cortar o enjoo do feijão',
      'Ferva o feijão sem tampa para não escurecer',
      'Sobra de feijoada congela muito bem',
    ],
    imagem: '/images/placeholder.svg',
    slug: 'feijoada-lurdinha',
  },
  {
    id: '27',
    titulo: 'Patê de Frango com Cenoura',
    descricao: 'Patê cremoso de frango desfiado com cenoura ralada que serve de acompanhamento, recheio e até lanche',
    categoria: 'Acompanhamentos',
    tempoPreparo: 15,
    tempoTotal: 30,
    porcoes: 6,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Peito de frango cozido e desfiado', quantidade: '2 xícaras' },
      { item: 'Cenoura ralada fina', quantidade: '1/2 xícara' },
      { item: 'Maionese', quantidade: '1/2 xícara' },
      { item: 'Creme de leite', quantidade: '1/4 de xícara' },
      { item: 'Azeite', quantidade: '1 colher de sopa' },
      { item: 'Alho picado', quantidade: '1 dente' },
      { item: 'Salsinha picada', quantidade: '2 colheres de sopa' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Refogue o alho no azeite até dourar levemente.',
      'Adicione o frango desfiado e a cenoura, misture bem.',
      'Cozinhe por 3 minutos para secar o excesso de líquido.',
      'Retire do fogo e deixe esfriar.',
      'Misture a maionese, o creme de leite e a salsinha.',
      'Tempere com sal e pimenta.',
      'Leve à geladeira por 30 minutos antes de servir.',
      'Sirva com torradas, crackers ou como recheio de pão de forma.',
    ],
    dicas: [
      'Use frango bem temperado para mais sabor',
      'Rale a cenoura fina para não ficar dura no patê',
      'Dura até 3 dias na geladeira se bem fechado',
    ],
    imagem: '/images/placeholder.svg',
    slug: 'pate-frango-cenoura',
  },
  {
    id: '28',
    titulo: 'Pipoca Doce de Leite Condensado',
    descricao: 'Pipoca caramelizada com leite condensado que vira vício em noites de filme em casa',
    categoria: 'Lanches',
    tempoPreparo: 5,
    tempoTotal: 15,
    porcoes: 4,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Milho de pipoca', quantidade: '1/2 xícara' },
      { item: 'Óleo', quantidade: '2 colheres de sopa' },
      { item: 'Manteiga', quantidade: '2 colheres de sopa' },
      { item: 'Leite condensado', quantidade: '1/2 lata' },
      { item: 'Açúcar mascavo', quantidade: '2 colheres de sopa' },
      { item: 'Sal', quantidade: '1 pitada' },
    ],
    modoPreparo: [
      'Em uma panela grande com tampa, aqueça o óleo e o milho de pipoca em fogo alto.',
      'Quando começar a estourar, abaixe o fogo e vá sacudindo a panela de vez em quando.',
      'Espere até que os estouros diminuam e reserve a pipoca em uma tigela.',
      'Na mesma panela, derreta a manteiga e adicione o açúcar mascavo.',
      'Mexa até formar um caramelo claro.',
      'Adicione o leite condensado e uma pitada de sal, misturando bem.',
      'Despeje o caramelo quente sobre a pipoca e misture rápido com duas colheres.',
      'Espalhe em uma assadeira para esfriar e não grudar.',
    ],
    dicas: [
      'Use panela grande para a pipoca não transbordar',
      'Misture o caramelo logo enquanto está quente',
      'Pode adicionar amendoim torrado para dar crocância',
    ],
    imagem: '/images/placeholder.svg',
    slug: 'pipoca-doce-leite-condensado',
  },
  {
    id: '29',
    titulo: 'Pipoca de Chocolate Crocante',
    descricao: 'Pipoca coberta com chocolate meio amargo, crocante por fora e macia por dentro',
    categoria: 'Lanches',
    tempoPreparo: 5,
    tempoTotal: 25,
    porcoes: 4,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Milho de pipoca', quantidade: '1/2 xícara' },
      { item: 'Óleo', quantidade: '2 colheres de sopa' },
      { item: 'Chocolate meio amargo', quantidade: '200g' },
      { item: 'Manteiga', quantidade: '1 colher de sopa' },
      { item: 'Sal', quantidade: '1 pitada' },
      { item: 'Granulado', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Prepare a pipoca na panela com o óleo, até estourar bem.',
      'Separe a pipoca em uma assadeira e retire os milhos que não estouraram.',
      'Derreta o chocolate com a manteiga em banho-maria ou micro-ondas de 30 em 30 segundos.',
      'Despeje o chocolate sobre a pipoca, misturando bem.',
      'Espalhe em uma assadeira forrada com papel manteiga.',
      'Polvilhe o granulado antes do chocolate endurecer.',
      'Leve à geladeira por 10 minutos para ficar crocante.',
      'Sirva em seguida.',
    ],
    dicas: [
      'Use pipoca sem manteiga para o chocolate grudar melhor',
      'Chocolate muito quente pode murchar a pipoca',
      'Armazene em pote fechado para manter a crocância',
    ],
    imagem: '/images/placeholder.svg',
    slug: 'pipoca-chocolate-crocante',
  },
  {
    id: '30',
    titulo: 'Caldinho de Feijão Preto da Lurdinha',
    descricao: 'Caldinho de feijão preto cremoso, com gostinho de boteco e cheiro de casa de mãe',
    categoria: 'Sopas',
    tempoPreparo: 15,
    tempoTotal: 40,
    porcoes: 4,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Feijão preto cozido', quantidade: '3 xícaras' },
      { item: 'Caldo de feijão', quantidade: '2 xícaras' },
      { item: 'Bacon em cubos', quantidade: '100g' },
      { item: 'Linguiça calabresa', quantidade: '1 unidade' },
      { item: 'Cebola', quantidade: '1 unidade' },
      { item: 'Alho', quantidade: '3 dentes' },
      { item: 'Coentro', quantidade: 'a gosto' },
      { item: 'Azeite', quantidade: '2 colheres de sopa' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Refogue a cebola e o alho no azeite.',
      'Adicione o bacon e a linguiça em rodelas, frite até dourar.',
      'Acrescente o feijão escorrido e uma parte do caldo.',
      'Bata no liquidificador até metade da mistura e volte para a panela.',
      'Adicione o restante do caldo até ficar na consistência desejada.',
      'Cozinhe por 15 minutos em fogo médio.',
      'Tempere com sal e pimenta.',
      'Sirva bem quente com coentro por cima.',
    ],
    dicas: [
      'Use feijão bem cozido para um caldinho encorpado',
      'Bater metade dá cremosidade sem perder o caldo grosso',
      'Fica perfeito com torradas de pão francês',
    ],
    imagem: '/images/placeholder.svg',
    slug: 'caldinho-feijao-preto',
  },
  {
    id: '31',
    titulo: 'Caldinho de Camarão com Leite de Coco',
    descricao: 'Caldinho de camarão cremoso e levemente picante, típico das praias do Nordeste',
    categoria: 'Sopas',
    tempoPreparo: 20,
    tempoTotal: 35,
    porcoes: 4,
    dificuldade: 'médio',
    ingredientes: [
      { item: 'Camarão médio limpo', quantidade: '400g' },
      { item: 'Leite de coco', quantidade: '1 lata' },
      { item: 'Caldo de camarão ou peixe', quantidade: '2 xícaras' },
      { item: 'Cebola', quantidade: '1 unidade' },
      { item: 'Alho', quantidade: '2 dentes' },
      { item: 'Tomate', quantidade: '2 unidades' },
      { item: 'Coentro', quantidade: 'a gosto' },
      { item: 'Azeite', quantidade: '2 colheres de sopa' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
      { item: 'Pimenta dedo-de-moça', quantidade: '1 unidade' },
    ],
    modoPreparo: [
      'Refogue a cebola, o alho e o tomate picado no azeite.',
      'Adicione os camarões e cozinhe por 3 minutos.',
      'Acrescente o caldo, o leite de coco e a pimenta.',
      'Cozinhe por 10 minutos em fogo baixo sem ferver.',
      'Tempere com sal e pimenta.',
      'Finalize com coentro e sirva com torradas.',
    ],
    dicas: [
      'Cuidado para não cozinhar o camarão demais, pode ficar borrachudo',
      'Use camarão bem fresco ou congelado de qualidade',
      'Caldo caseiro de peixe deixa o sabor ainda melhor',
    ],
    imagem: '/images/placeholder.svg',
    slug: 'caldinho-camarao-coco',
  },
  {
    id: '32',
    titulo: 'Caldo Verde da Lurdinha',
    descricao: 'Caldo verde cremoso de batata com couve e linguiça, confortante e cheio de sabor',
    categoria: 'Sopas',
    tempoPreparo: 20,
    tempoTotal: 50,
    porcoes: 6,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Batatas médias', quantidade: '6 unidades' },
      { item: 'Couve manteiga fatiada fina', quantidade: '2 xícaras' },
      { item: 'Linguiça calabresa', quantidade: '1 unidade' },
      { item: 'Alho', quantidade: '3 dentes' },
      { item: 'Cebola', quantidade: '1 unidade' },
      { item: 'Azeite', quantidade: '2 colheres de sopa' },
      { item: 'Caldo de legumes', quantidade: '1 litro' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Refogue a cebola e o alho no azeite.',
      'Adicione as batatas em cubos e o caldo de legumes.',
      'Cozinhe até as batatas estarem bem moles.',
      'Bata a sopa no liquidificador até ficar cremosa.',
      'Volte para a panela, adicione a couve e a linguiça em rodelas.',
      'Cozinhe por mais 5 minutos.',
      'Tempere com sal e pimenta e sirva quente.',
    ],
    dicas: [
      'Fatie a couve bem fininha para não ficar dura',
      'Cozinhe a couve pouco para manter a cor verde',
      'Se preferir, troque a calabresa por paio',
    ],
    imagem: '/images/sopa-abobora-gengibre.jpg',
    slug: 'caldo-verde-lurdinha',
  },
  {
    id: '33',
    titulo: 'Caldo de Quenga da Lurdinha',
    descricao: 'Caldo grosso de mandioca com costela e linguiça, comida de raiz para esquentar o corpo',
    categoria: 'Sopas',
    tempoPreparo: 25,
    tempoTotal: 90,
    porcoes: 6,
    dificuldade: 'médio',
    ingredientes: [
      { item: 'Mandioca descascada', quantidade: '1kg' },
      { item: 'Costela de boi', quantidade: '500g' },
      { item: 'Linguiça paio', quantidade: '2 unidades' },
      { item: 'Cebola', quantidade: '1 unidade' },
      { item: 'Alho', quantidade: '3 dentes' },
      { item: 'Coentro', quantidade: 'a gosto' },
      { item: 'Azeite', quantidade: '2 colheres de sopa' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
    ],
    modoPreparo: [
      'Cozinhe a costela e a linguiça em água até começarem a ficar macias.',
      'Adicione a mandioca em pedaços e cozinhe até desmanchar.',
      'Em outra panela, refogue a cebola e o alho no azeite.',
      'Acrescente o refogado ao caldo com a mandioca.',
      'Bata metade do caldo no liquidificador para ficar cremoso.',
      'Volte para a panela, tempere com sal e pimenta.',
      'Finalize com coentro e sirva bem quente.',
    ],
    dicas: [
      'Quanto mais a mandioca desmanchar, mais grosso fica o caldo',
      'Costela de boi demora, mas dá o sabor especial',
      'Sobra fica ainda melhor no dia seguinte',
    ],
    imagem: '/images/placeholder.svg',
    slug: 'caldo-quenga-lurdinha',
  },
  {
    id: '34',
    titulo: 'Almôndegas de Carne Moída na Panela',
    descricao: 'Almôndegas macias e suculentas com molho de tomate caseiro, uma salvação para o almoço de domingo',
    categoria: 'Pratos Principais',
    tempoPreparo: 20,
    tempoTotal: 50,
    porcoes: 5,
    dificuldade: 'fácil',
    ingredientes: [
      { item: 'Carne moída de acém', quantidade: '500g' },
      { item: 'Ovo', quantidade: '1 unidade' },
      { item: 'Farinha de rosca', quantidade: '1/2 xícara' },
      { item: 'Alho picado', quantidade: '2 dentes' },
      { item: 'Cebola picada', quantidade: '1/2 unidade' },
      { item: 'Salsinha', quantidade: '2 colheres de sopa' },
      { item: 'Sal e pimenta', quantidade: 'a gosto' },
      { item: 'Óleo para fritar', quantidade: 'a gosto' },
      { item: 'Molho de tomate caseiro', quantidade: '2 xícaras' },
    ],
    modoPreparo: [
      'Misture a carne, o ovo, a farinha de rosca, o alho, a cebola, a salsinha, o sal e a pimenta.',
      'Modele bolinhas do tamanho de uma noz.',
      'Frite levemente no óleo quente para dourar as bordas.',
      'Retire e reserve em papel toalha.',
      'Na mesma panela, aqueça o molho de tomate com um pouco de água.',
      'Coloque as almôndegas no molho e cozinhe por 15 minutos.',
      'Sirva com arroz e purê de batata.',
    ],
    dicas: [
      'Molhe as mãos para modelar sem grudar',
      'Não amasse muito a carne para as almôndegas ficarem macias',
      'Pode congelar cruas e fritar na hora',
    ],
    imagem: '/images/tacos-carnitas.jpg',
    slug: 'almondegas-carne-moida',
  },
];

// Função para obter todas as receitas
export function getAllRecipes(): Recipe[] {
  return recipes;
}

// Função para obter receita por slug
export function getRecipeBySlug(slug: string): Recipe | undefined {
  return recipes.find((recipe) => recipe.slug === slug);
}

// Função para obter receitas por categoria
export function getRecipesByCategory(category: string): Recipe[] {
  return recipes.filter((recipe) => recipe.categoria === category);
}

// Função para obter todas as categorias únicas
export function getAllCategories(): string[] {
  const categories = new Set(recipes.map((recipe) => recipe.categoria));
  return Array.from(categories).sort();
}

// Função para buscar receitas por termo
export function searchRecipes(term: string): Recipe[] {
  const lowerTerm = term.toLowerCase();
  return recipes.filter(
    (recipe) =>
      recipe.titulo.toLowerCase().includes(lowerTerm) ||
      recipe.descricao.toLowerCase().includes(lowerTerm) ||
      recipe.ingredientes.some((ing) =>
        ing.item.toLowerCase().includes(lowerTerm)
      )
  );
}
